#include "odm_spine.h"
#include "odm_build_meta.h"
#include "spine_internal.h"

enum {
#define ODM_MODULE(symbol, id, name, path, layer, role) ODM_MODULE_ID_##symbol = id,
#define ODM_DEP(module, dependency)
#include "modules.def"
#undef ODM_DEP
#undef ODM_MODULE
};

static const odm_spine_module odm_registry_modules[] = {
#define ODM_MODULE(symbol, id, name, path, layer, role) \
    {id, name, path, layer, ODM_MODULE_LINES_##symbol, role},
#define ODM_DEP(module, dependency)
#include "modules.def"
#undef ODM_DEP
#undef ODM_MODULE
};

static const odm_spine_dependency odm_registry_dependencies[] = {
#define ODM_MODULE(symbol, id, name, path, layer, role)
#define ODM_DEP(module, dependency) \
    {(uint32_t)ODM_MODULE_ID_##module, (uint32_t)ODM_MODULE_ID_##dependency},
#include "modules.def"
#undef ODM_DEP
#undef ODM_MODULE
};

static const odm_spine_invariant odm_registry_invariants[] = {
    {"TIME-1", ODM_MODULE_ID_TIME,
     "Every supported frame boundary is an exact 48 kHz sample coordinate and output end is checked before publication.",
     "Integral samples-per-frame, checked int64 multiplication and quotient/remainder ceiling.",
     "tests/unit/test_time.c"},
    {"TIME-2", ODM_MODULE_ID_TIME,
     "Default soundtrack handling never truncates audio and accounts for authored post-roll plus exact alignment silence.",
     "Project end is soundtrack samples plus authored post-roll; silence extends to output_end_sample.",
     "tests/unit/test_time.c"},
    {"FIX-1", ODM_MODULE_ID_FIXED,
     "Canonical fixed-point operations use nearest ties away from zero and report overflow instead of wrapping signed values.",
     "Portable limb multiplication and checked signed reconstruction without native floating point.",
     "tests/unit/test_fixed.c"},
    {"RNG-1", ODM_MODULE_ID_RNG,
     "Render-semantic randomness is explicit, seeded and reproducible from stable domain/entity identifiers.",
     "PCG32 XSH-RR with frozen seed procedure, initialization cookie and deterministic SplitMix64 domain derivation.",
     "tests/unit/test_rng.c"},
    {"MEM-1", ODM_MODULE_ID_MEMORY_BUDGET,
     "Concurrent reservations never exceed the configured limit and uint64 wraparound cannot admit work.",
     "Compare/exchange reservation loop checks subtraction bounds before publication.",
     "tests/unit/test_memory.c"},
    {"MEM-2", ODM_MODULE_ID_ARENA,
     "Arena allocations are aligned, bounded and rewound only to a valid earlier mark.",
     "Checked padding/addition against one explicit capacity and optional clearing on rewind.",
     "tests/unit/test_memory.c"},
    {"OWN-1", ODM_MODULE_ID_OWNERSHIP,
     "Every owned allocation has one ledger owner, explicit release, or explicit transfer; destroy reclaims all remaining blocks.",
     "Intrusive owner-tagged headers, accounting, allocator identity checks and budget migration.",
     "tests/unit/test_memory.c"},
    {"PROGRESS-1", ODM_MODULE_ID_PROGRESS,
     "Published progress never exceeds completed work and never decreases within a job generation.",
     "Overflow-safe integer fraction plus atomic max publication.",
     "tests/unit/test_job.c"},
    {"JOB-1", ODM_MODULE_ID_JOB,
     "Accepted cancellation cannot become successful completion and stale workers cannot update a reused job.",
     "One atomic control word binds state, cancellation and a 48-bit generation ticket.",
     "tests/unit/test_job.c"},
    {"SPINE-1", ODM_MODULE_ID_SPINE,
     "The compiled module registry is unique, layer-consistent, acyclic and serializes without silent truncation.",
     "Runtime validation, independent filesystem/symbol guardian and size-first JSON contract.",
     "tests/unit/test_spine.c"},
    {"BUILD-1", ODM_MODULE_ID_VERSION,
     "Build identity excludes wall-clock macros and is stable for identical source and toolchain inputs.",
     "Content-derived SHA-256 source identity, prefix mapping and reproducible-build comparison.",
     "tests/determinism/check_reproducible.py"},
    {"HASH-1", ODM_MODULE_ID_HASH,
     "SHA-256 bytes are endian-neutral, streaming-equivalent and never accept a corrupt or finalized context.",
     "Checked FIPS 180-4 state machine, 64-bit length ceiling, canonical lowercase hex and constant-time digest comparison.",
     "tests/unit/test_hash.c"},
    {"WIRE-1", ODM_MODULE_ID_WIRE,
     "Canonical records have one fixed little-endian byte representation with explicit wire/schema versions and SHA-256 payload identity.",
     "Fixed 64-byte ODMC header, zero reserved fields, exact total length and byte-for-byte golden vectors.",
     "tests/unit/test_wire.c"},
    {"WIRE-2", ODM_MODULE_ID_WIRE,
     "Truncation, trailing bytes, unknown versions, reserved flags and digest mismatch never publish a partial decoded record.",
     "Transactional temporary decode plus sticky bounded cursors and fail-closed integrity verification.",
     "tests/unit/test_wire.c"},
    {"LIMIT-1", ODM_MODULE_ID_LIMITS,
     "Every admitted resource request is within each explicit non-zero ceiling and arithmetic overflow cannot reduce a quote.",
     "Versioned fixed-width limits, deterministic first-failure dimensions and checked uint64 add/multiply.",
     "tests/unit/test_limits.c"},
    {"ABI-1", ODM_MODULE_ID_FFI,
     "ABI v1 layout and features are queried explicitly and FFI outputs are exact-size copied buffers with no borrowed engine lifetime.",
     "Fixed-width 64-byte discovery structure, compile-time layout assertions and size-first adapters.",
     "tests/unit/test_ffi.c"},
    {"EXEC-1", ODM_MODULE_ID_EXECUTOR,
     "Outstanding work is bounded, every accepted task owns one generational job ticket, and accepted cancellation cannot publish success.",
     "One preallocated slot/queue block, mutex-protected FIFO admission, cooperative job cancellation and joined fail-closed shutdown.",
     "tests/unit/test_executor.c"},
    {"PERF-1", ODM_MODULE_ID_EXECUTOR,
     "Gate 1 core throughput must meet explicit non-zero SHA-256, canonical-wire and bounded-executor floors on the evidence host.",
     "Monotonic-clock release benchmark processes fixed byte/task volumes and exits non-zero below any frozen threshold.",
     "bench/benchmark_core.c"},
    {"MEDIA-1", ODM_MODULE_ID_MEDIA_PROBE,
     "Recognizing a media signature never implies that a decoder is implemented or accepted.",
     "Probe returns an explicit supported/recognized-only state and dispatch refuses recognized-only formats.",
     "tests/unit/test_media.c"},
    {"MEDIA-2", ODM_MODULE_ID_MEDIA_DISPATCH,
     "A corrupt supported WAV/PNG preserves its real parse or integrity failure instead of being relabeled unsupported.",
     "Dispatch selects by signature first and forwards the selected adapter failure without fallback promotion.",
     "tests/unit/test_media.c"},
    {"MEDIA-3", ODM_MODULE_ID_MEDIA_FACTS,
     "Published Media Facts are canonical, source-addressed and round-trip through one versioned ODMC record.",
     "Fixed 160-byte payload, explicit zero reserved bytes, SHA-256 source/decoded identities and transactional decode.",
     "tests/unit/test_media.c"},
    {"MEDIA-4", ODM_MODULE_ID_WAV,
     "RIFF/WAVE chunk traversal is bounded by the declared RIFF extent and rejects truncation, duplicate semantic chunks and malformed padding.",
     "Checked uint64 offsets and exact RIFF extent before any sample publication.",
     "tests/unit/test_media.c"},
    {"MEDIA-5", ODM_MODULE_ID_WAV,
     "Accepted WAV format metadata is internally self-consistent.",
     "Channels, bit depth, block-align and byte-rate are cross-checked before decoding.",
     "tests/unit/test_media.c"},
    {"MEDIA-6", ODM_MODULE_ID_PCM,
     "Canonical decoded audio is signed stereo Q1.31 with no native floating-point arithmetic as semantic authority.",
     "Integer PCM scaling and direct IEEE-754 bit-field conversion with deterministic saturation.",
     "tests/unit/test_media.c"},
    {"MEDIA-7", ODM_MODULE_ID_PCM,
     "Mono WAV is duplicated exactly to both canonical channels and stereo preserves channel order.",
     "One explicit sample conversion path per source channel and deterministic mono duplication.",
     "tests/unit/test_media.c"},
    {"MEDIA-8", ODM_MODULE_ID_MEDIA_LIMITS,
     "Canonical 48 kHz duration uses exact rational ceiling and cannot undercount a non-integral source-rate conversion.",
     "Overflow-safe 128-by-64 integer ceil multiply/divide; 44.1 kHz edge cases are regression tested.",
     "tests/unit/test_media.c"},
    {"MEDIA-9", ODM_MODULE_ID_PNG_CRC,
     "PNG chunk bounds and CRCs are verified independently before libpng decode.",
     "Fail-closed chunk walker with CRC-32 over type+payload and exact IEND termination.",
     "tests/unit/test_media.c"},
    {"MEDIA-10", ODM_MODULE_ID_PNG_CRC,
     "PNG dimensions cannot overflow or exceed the explicit pixel admission ceiling.",
     "IHDR validation plus checked width*height against fixed limits.",
     "tests/unit/test_media.c"},
    {"MEDIA-11", ODM_MODULE_ID_PNG,
     "Image pixels and Media Facts publish together only after a complete successful decode.",
     "Decode into bounded temporary storage, validate/hash it, then copy transactionally to caller storage.",
     "tests/unit/test_media.c"},
    {"MEDIA-12", ODM_MODULE_ID_MEDIA_DISPATCH,
     "Formats without a real adapter fail closed even when their signatures are known.",
     "Recognized-only FLAC/JPEG/WebP/MP3/ISO-BMFF/WebM states are never promoted to supported.",
     "tests/unit/test_media.c"},
    {"MUSIC-RESAMPLE-1", ODM_MODULE_ID_RESAMPLE,
     "Canonical resampling publishes exact 48 kHz stereo Q1.31 with deterministic phase/tap policy, exact output duration and bit-exact 48 kHz bypass.",
     "Frozen 1024-phase integer polyphase Lanczos/FIR plan, Q30-normalized coefficient rows, exact rational duration and no native floating-point semantic authority.",
     "tests/unit/test_resample.c"},
    {"MUSIC-RESAMPLE-2", ODM_MODULE_ID_RESAMPLE,
     "A resampling plan cannot silently change coefficients or exceed bounded work, and cancellation/saturation are explicit outcomes.",
     "SHA-256-bound little-endian coefficient table identity, 64..512 bounded taps, cooperative job tickets and counted Q1.31 saturation.",
     "tests/unit/test_resample.c"},
    {"MUSIC-MAP-1", ODM_MODULE_ID_MUSIC_ANALYSIS,
     "Canonical analysis coordinates are exactly 100 Hz over 48 kHz PCM with a centered 2048-sample periodic-Hann transform and zero padding outside signal bounds.",
     "480-sample tick coordinates, fixed Q1.31 Hann/twiddle tables and deterministic scaled radix-2 FFT.",
     "tests/unit/test_music_analysis.c"},
    {"MUSIC-MAP-2", ODM_MODULE_ID_MUSIC_ANALYSIS,
     "Exact feature vectors use frozen integer formulas and sequential state is explicit rather than inferred from wall-clock execution.",
     "Q1.31 RMS/energy, six fixed contiguous spectral bands, 1/4-1/16-1/64 envelopes, flux, centroid, delta, silence and stereo measures.",
     "tests/unit/test_music_analysis.c"},
    {"MUSIC-MAP-3", ODM_MODULE_ID_MUSIC_ANALYSIS,
     "Onset, beat, BPM, phrase, section and semantic labels cannot overwrite or masquerade as canonical exact Music Map facts.",
     "The exact v1 tick schema contains only deterministic signal-derived features; inference remains outside this API.",
     "tests/unit/test_music_analysis.c"},
    {"MUSIC-POLICY-1", ODM_MODULE_ID_MUSIC_ANALYSIS,
     "Every canonical Music Map is bound to one byte-exact analysis policy identity.",
     "A fixed 192-byte little-endian policy record binds timeline, resampler contract, bands, envelopes, silence threshold and window/twiddle SHA-256 identities.",
     "tests/unit/test_music_analysis.c"},
    {"MUSIC-REACTION-1", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "High-resolution reaction inference can never overwrite or masquerade as canonical Music Map v1 truth.",
     "Reaction Spine v1 is a separately versioned derived stream consuming only the deterministic analyzer spectrum scratch after a canonical tick; Music Map v1 bytes and policy remain unchanged.",
     "tools/check_music_reaction_oracle.py"},
    {"MUSIC-REACTION-2", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "Every visible reactive radial amplitude is traceable to an explicit local spectral lane and cannot be modulated by autonomous procedural time phase.",
     "Ninety-six frozen contiguous lanes feed ninety-six high-resolution radials one-to-one; the legacy forty-eight-radial path is a deterministic adjacent-pair reduction, and the independent oracle changes project time while requiring stationary reaction phase and byte-identical amplitudes.",
     "tools/check_music_reaction_oracle.py"},
    {"MUSIC-REACTION-3", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "An isolated extreme spectral outlier cannot become the normalization authority for an entire track.",
     "Magnitude references use an exact deterministic P99 order statistic and attacks use exact P95 over positive deltas only, selected allocation-free by four radix passes.",
     "tools/check_music_reaction_oracle.py"},
    {"MUSIC-REACTION-4", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "A reaction event is causal at the current tick: its threshold cannot incorporate that same tick before deciding whether the event occurred.",
     "The adaptive threshold is resolved from prior history, then same-tick attack is evaluated, then the current evidence is folded into state with an explicit refractory and decaying pulse.",
     "tests/unit/test_music_reaction.c"},
    {"MUSIC-REACTION-5", ODM_MODULE_ID_REACTIVE_FIELD_LAYER,
     "High-resolution reaction geometry must survive the compositor boundary as ninety-six independently addressable radials while the legacy forty-eight-radial raster remains reproducible.",
     "The layered plan preserves ninety-six lanes one-to-one for hi-res configurations, deterministically reduces adjacent pairs for legacy configurations, and an independent pixel oracle reconstructs the ninety-six-radial CORDIC projection and blend stream.",
     "tools/check_radial_hires_geometry_oracle.py"},
    {"MUSIC-REACTION-6", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "Music-Reaction temporal semantics are part of canonical policy identity and cannot drift while retaining the same policy SHA-256.",
     "A fixed 512-byte Music-Reaction Policy v6 record binds lane/family topology, magnitude and attack normalization, shaping, frequency-aware release, coherent global-event scoring, refractory/pulse decay, local-candidate offline refinement, contextual salience calibration and causal presentation-projection semantics; every serialized track profile embeds that policy SHA-256.",
     "tools/check_music_reaction_oracle.py"},
    {"MUSIC-REACTION-7", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "Offline event refinement may relocate only macro onset publication to a bounded local evidence maximum; it cannot rewrite spectral evidence, timestamps, thresholds or masquerade as beat/BPM inference.",
     "The complete frame sequence is preflighted transactionally; eligible plus/minus-two-tick local maxima use deterministic earliest-tie selection, a policy-bound nearest-rank median is computed only across those legitimate local candidates rather than silence/all ticks, refractory is enforced, and the event pulse is reconstructed from selected peaks.",
     "tools/check_music_reaction_oracle.py"},
    {"MUSIC-REACTION-8", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "Temporal persistence is frequency-aware without inventing energy: low-frequency envelopes may release more slowly than air/presence, while every envelope remains bounded by current evidence or monotonic decay of prior evidence.",
     "Six policy-bound integer release divisors map lane centers and family envelopes to deterministic tails; broadband uses its own bounded divisor and an independent oracle reconstructs exact Q1.31 release values.",
     "tools/check_music_reaction_oracle.py"},
    {"MUSIC-REACTION-9", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "Presentation frame rate cannot erase or anticipate instantaneous Music-Reaction evidence.",
     "Causal Presentation Projection holds sustained fields from the latest source tick at or before the presentation sample while max/OR-aggregating attacks and event strength/flags exactly once over (previous,current]; an independent oracle reconstructs the mapping at 24/25/30/50/60/100/120 fps and rejects future leakage or duplicate/lost source ticks.",
     "tools/check_reaction_projection_oracle.py"},
    {"MUSIC-REACTION-10", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "A single narrow spectral lane cannot promote itself into a global scene impact, and silence/non-candidate ticks cannot define the offline macro gate.",
     "Global event score is max(broadband attack, second-strongest family attack); event strength combines broadband plus the two strongest families, while offline macro selection derives its policy-bound order statistic only from validated local onset candidates.",
     "tools/check_music_reaction_oracle.py"},
    {"MUSIC-REACTION-11", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "Robust attack normalization cannot collapse every attack above the P95 reference to one saturated value.",
     "Policy v5 maps the P95 reference to 0.70 Q1.31 and maps the remaining raw attack domain monotonically into the remaining headroom up to one, preserving exceptional-transient ordering without adding a floor.",
     "tools/check_music_reaction_oracle.py"},
    {"MUSIC-REACTION-12", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "A seek or malformed presentation schedule cannot replay historical transients or publish a partially projected reaction timeline.",
     "The first nonzero presentation opens only (sample-1,sample], complete schedules are preflighted before publication, and oversized causal intervals are rejected by a policy-bound one-second scan budget.",
     "tools/check_reaction_projection_oracle.py"},
    {"MUSIC-REACTION-13", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "Full-track contextual normalization cannot overwrite or masquerade as raw causal event evidence.",
     "Offline refinement preserves event_strength as the physical/coherent onset evidence and publishes track-context macro_salience plus macro_pulse in separate explicitly flagged fields; streaming frames cannot populate those contextual fields.",
     "tools/check_music_reaction_oracle.py"},
    {"MUSIC-REACTION-14", ODM_MODULE_ID_MUSIC_REACTION_SPINE,
     "Silence, sustain and rejected narrow excursions cannot define the scale of contextual macro salience or gain global composition authority merely because they are frequent.",
     "Contextual references are exact P10/P95 order statistics computed only over macro-gated legitimate local onset candidates; presentation projection rejects mixed contextual/evidence-only streams and preserves macro impulses causally across frame rates.",
     "tools/check_reaction_projection_oracle.py"},
    {"MUSIC-REACTION-15", ODM_MODULE_ID_VISUAL_PROCEDURAL,
     "Global visual axes and structural scene changes cannot be promoted by one narrow spectral excursion or by a transfer coefficient masquerading as measured activity.",
     "Multi-axis composition maps low attack, mid/body, presence/air and exceptional contextual salience to separate bounded authorities; STRICT_CAUSAL Director orbit candidacy derives from the mean visible radial evidence rather than radial_gain.",
     "tools/check_multi_axis_visual_oracle.py"},
    {"MUSIC-WIRE-1", ODM_MODULE_ID_MUSIC_MAP_WIRE,
     "analysis.bin has one canonical little-endian representation bound to canonical PCM and the exact music-policy SHA-256.",
     "A fixed 128-byte payload header and fixed 128-byte tick records are wrapped in ODMC with exact length and SHA-256 integrity.",
     "tests/unit/test_music_map_wire.c"},
    {"MUSIC-WIRE-2", ODM_MODULE_ID_MUSIC_MAP_WIRE,
     "Corrupt, truncated, trailing, version-mismatched or semantically inconsistent Music Maps never publish partial decoded ticks.",
     "Two-pass fail-closed validation precedes caller-buffer publication and validates tick indices, centers and reserved fields.",
     "tests/unit/test_music_map_wire.c"},
    {"SCORE-1", ODM_MODULE_ID_SCORE,
     "Visual Score v1 accepts only bounded, ordered, versioned authoring data and rejects reserved or unsupported semantics.",
     "Fixed-width records, explicit ceilings, monotonic identifiers and fail-closed capability lookup.",
     "tests/unit/test_score_ir.c"},
    {"SCORE-2", ODM_MODULE_ID_SCORE,
     "Every act is exactly covered by one or two-scene overlap topology; each scene owns exactly one black-void environment and one primary node.",
     "Gap-free act/scene validation, triple-overlap rejection and exact role-node identity checks.",
     "tests/unit/test_score_ir.c"},
    {"SCORE-3", ODM_MODULE_ID_SCORE,
     "Capability versions, role masks, resource kinds and state models are explicit inputs to score identity.",
     "Frozen capability registry plus capability-set SHA-256 included in Render IR.",
     "tests/unit/test_score_ir.c"},
    {"SCORE-4", ODM_MODULE_ID_SCORE,
     "Automation and music modulation cannot silently overlap invalid ranges or target unsupported parameter/source combinations.",
     "Sorted target ranges, interval non-overlap, bounded micro-units and exact Music Map feature IDs.",
     "tests/unit/test_score_ir.c"},
    {"IR-1", ODM_MODULE_ID_SCORE_COMPILER,
     "A valid Score compiles to one canonical little-endian Render IR byte stream with exact section sizes and content identity.",
     "Size-first checked arithmetic, fixed section order/record widths and ODMC SHA-256 envelope.",
     "tests/unit/test_score_ir.c"},
    {"IR-2", ODM_MODULE_ID_RENDER_IR,
     "Render IR never trusts its outer hash alone; semantic corruption, unknown capability/schema or inconsistent timeline fails closed.",
     "Full semantic revalidation of capabilities, resources, timeline, nodes, modulation, automation, transitions, transfers and output.",
     "tests/unit/test_score_ir.c"},
    {"FRAME-1", ODM_MODULE_ID_FRAME_STATE,
     "Every resolved frame uses the exact integral sample coordinate and only the Music Map tick belonging to that coordinate.",
     "Checked frame multiplication plus canonical 480-sample tick binding and exact synthetic-silence boundary.",
     "tests/unit/test_score_ir.c"},
    {"FRAME-2", ODM_MODULE_ID_FRAME_STATE,
     "Frame State publication is transactional: invalid music, arithmetic overflow or insufficient output capacity publishes no partial node state.",
     "Requirements pass and arithmetic preflight complete before writing caller-owned node/transfer arrays.",
     "tests/unit/test_score_ir.c"},
    {"PKG-1", ODM_MODULE_ID_ODPARMS,
     ".odparms has one strict ZIP32 interpretation with canonical safe names, exact local/central agreement and no gaps, overlaps, extras, comments, encryption or data descriptors.",
     "Deterministic zero-timestamp ZIP32 profile with contiguous local records and exact central-directory extent.",
     "tests/unit/test_package.c"},
    {"PKG-2", ODM_MODULE_ID_PACKAGE_SIGN,
     "The package manifest is authenticated by Ed25519 and an expected external public key, when supplied, must match before trust is accepted.",
     "Exact manifest-byte signature plus constant-time public-key comparison and RFC 8032 vectors.",
     "tests/unit/test_package.c"},
    {"PKG-3", ODM_MODULE_ID_ODPARMS,
     "Score, capability set, Render IR, Music Map and current Music Policy identities must agree transitively before build or verification succeeds.",
     "Semantic revalidation of Render IR and analysis.bin against manifest SHA-256 identities.",
     "tests/unit/test_package.c"},
    {"PKG-4", ODM_MODULE_ID_PACKAGE_DEFLATE,
     "Compressed package data cannot expand outside explicit entry, total-size and ratio budgets and canonical writer output is deterministic.",
     "Bounded 32 KiB window, fixed-Huffman-only reader/writer, size-first compression and preflight expansion ceilings.",
     "tests/unit/test_package.c"},
    {"PKG-5", ODM_MODULE_ID_ODPARMS,
     "Package build, verify and extract do not publish partial caller-visible results on validation, integrity or capacity failure.",
     "Full prevalidation and sizing precede writes; extraction verifies the complete package before copying decoded payload bytes.",
     "tests/unit/test_package.c"},
    {"RENDER-1", ODM_MODULE_ID_REFERENCE_RENDERER,
     "Reference rendering is a pure function of validated Render IR, exact Frame State, canonical assets and explicit frame index; wall clock and direct audio are never semantic inputs.",
     "Renderer consumes only validated IR/Frame State and admitted surface assets at the canonical 48 kHz-derived frame sample.",
     "tests/unit/test_renderer.c"},
    {"RENDER-2", ODM_MODULE_ID_RENDER_COLOR,
     "Reference pixels use one versioned linear-light BT.709 premultiplied fixed-point color domain before canonical RGBA16LE publication.",
     "Frozen sRGB EOTF table, Q4.27 RGB, Q1.31 alpha, integer source-over and ties-away conversion to 16-bit channels.",
     "tests/unit/test_renderer.c"},
    {"RENDER-3", ODM_MODULE_ID_RENDER_SAMPLER,
     "Image and video sampling uses deterministic fixed-point inverse transforms and bilinear interpolation with transparent out-of-bounds samples.",
     "Q32.32 normalized coordinates, uint32 phase CORDIC, exact quadrant shortcuts and four-texel linear-premultiplied interpolation.",
     "tests/unit/test_renderer.c"},
    {"RENDER-4", ODM_MODULE_ID_REFERENCE_RENDERER,
     "Scene transitions composite each scene independently before applying the canonical crossfade, preventing node-count-dependent opacity errors.",
     "Stable per-scene z ordering and exact Q1.31 scene interpolation after complete premultiplied scene composition.",
     "tests/unit/test_renderer.c"},
    {"RENDER-5", ODM_MODULE_ID_REFERENCE_RENDERER,
     "Every sampled asset is source-addressed to the Render IR resource and video frames are selected only from contiguous explicit local 48 kHz PTS intervals.",
     "Exact resource-id/kind/SHA matching and binary-search interval selection with fail-closed gaps.",
     "tests/unit/test_renderer.c"},
    {"RENDER-6", ODM_MODULE_ID_REFERENCE_RENDERER,
     "Rendering is transactional under capacity failure, invalid data and cancellation, and typed scratch is never accessed through an unaligned pointer.",
     "Whole-frame scratch publication, row-wise ticket checks, explicit 8-byte scratch alignment and late memcpy only after frame hashing.",
     "tests/unit/test_renderer.c"},
    {"RENDER-7", ODM_MODULE_ID_FRAME_ROOT,
     "Canonical frame identity binds IR, asset identity, frame/sample coordinates and exact pixels; frame roots accept one complete in-order frame sequence only.",
     "Domain-separated SHA-256 frame records and stateful sequential root accumulation with exact count/finalization checks.",
     "tests/unit/test_renderer.c"},
    {"FRAME-3", ODM_MODULE_ID_FRAME_STATE,
     "Stateful visual nodes have an explicit non-zero state_slot while stateless nodes have none, and Entry/Exit envelopes are exact sample-domain state rather than UI convention.",
     "Score/IR v1.1 validates state-slot ownership plus NONE/FADE_SCALE entry and exit durations; Frame State publishes exact Q1.31 envelope weights.",
     "tests/unit/test_visual.c"},
    {"VISUAL-1", ODM_MODULE_ID_VISUAL_HISTORY,
     "Visual Memory is rebuilt only from authored cues and explicit COPY/RESET State Transfer edges; RESET cuts ancestry and COPY can only cross matching state slots.",
     "Bounded reverse scene-chain traversal over validated Render IR with cycle/depth rejection and slot identity checks.",
     "tests/unit/test_visual.c"},
    {"VISUAL-2", ODM_MODULE_ID_VISUAL_HISTORY,
     "Event history is deterministic, latest-32 bounded and every event seed is derived from project seed, node seed-domain, state slot and cue identity.",
     "Stable SplitMix/PCG domain derivation, chronological timeline scan and deterministic oldest-event eviction.",
     "tests/unit/test_visual.c"},
    {"VISUAL-3", ODM_MODULE_ID_VISUAL_PROCEDURAL,
     "Grid, Halo, Residual Event Field and particle pixels are integer/fixed-point functions of canonical Frame State and Visual Memory only.",
     "No wall clock, native float or direct audio path; premultiplied Q1.31 output is bounded channel-by-channel and opacity INT32_MAX is exact identity.",
     "tests/unit/test_visual.c"},
    {"VISUAL-4", ODM_MODULE_ID_REFERENCE_RENDERER,
     "Stateful procedural history is resolved once per visible node and reused across its pixel loop, preserving deterministic semantics without per-pixel history reconstruction.",
     "Reference renderer precomputes node Visual Memory in typed scratch before rasterization and publishes the frame transactionally.",
     "tests/unit/test_visual.c"},
    {"VISUAL-5", ODM_MODULE_ID_VISUAL_PROCEDURAL,
     "Advanced Composition consumes canonical Music Map facts but never changes Music Map truth or calls a second audio-analysis path.",
     "A deterministic two-pass integer profile plus allocation-free sequential resolver maps existing exact tick fields into bounded composition state.",
     "tools/check_composition_oracle.py"},
    {"VISUAL-6", ODM_MODULE_ID_VISUAL_PROCEDURAL,
     "Visual Director changes macro-layout only through bounded dwell/novelty/impact rules and publishes one deterministic 128-byte layout state per consecutive tick.",
     "Caller-owned sequential state, minimum dwell, bounded transition timers, deterministic alternate selection and transactional batch preflight.",
     "tools/check_director_oracle.py"},
    {"VISUAL-7", ODM_MODULE_ID_VISUAL_PROCEDURAL,
     "Advanced Composition and Visual Director semantics are bound to one canonical Visual Policy SHA-256 independent of compiler ABI and C struct layout.",
     "A fixed 1024-byte little-endian policy serializes algorithm revisions, thresholds, dwell/transition rules, phase/alternate constants and every macro-layout target; unused bytes are canonical zero.",
     "tools/check_visual_policy_oracle.py"},
    {"VISUAL-8", ODM_MODULE_ID_VISUAL_PROCEDURAL,
     "Strict causal rendering is an explicit semantic authority independent of radial resolution; HIRES alone never implies causal isolation and STRICT_CAUSAL does not require HIRES.",
     "A dedicated Composition flag is propagated through Director and Layered plans, policy identities bind that separation, and an adversarial oracle exercises strict-without-hires plus hires-without-strict controls.",
     "tools/check_strict_causal_oracle.py"},
    {"VISUAL-9", ODM_MODULE_ID_VISUAL_PROCEDURAL,
     "In STRICT_CAUSAL mode identical typed musical evidence cannot produce different Director geometry because of seed, autonomous phase or stagnation alternates.",
     "The Director disables seed-selected stagnation alternates, pins autonomous phase/orbit/asymmetry to zero, and a 5000-tick metamorphic oracle compares unrelated seeds byte-for-byte.",
     "tools/check_director_oracle.py"},
    {"VISUAL-10", ODM_MODULE_ID_LAYERED_COMPOSITOR,
     "In STRICT_CAUSAL mode background and reactive-field pixels cannot change because of project time, composition phase/ring phase, Director orbit/asymmetry or field seed when musical evidence is unchanged.",
     "Grid offsets and ring phase are pinned to zero; strict particles use fixed index-derived spatial identity and music-derived visibility; a negative-control oracle proves the legacy procedural path remains sensitive.",
     "tools/check_strict_causal_oracle.py"},
    {"VISUAL-11", ODM_MODULE_ID_VISUAL_PROCEDURAL,
     "STRICT_CAUSAL Director decisions must measure visible musical evidence rather than control-transfer gain or caller seed state.",
     "The Director averages exactly the active 48/96 radial amplitudes for radial activity, uses that measurement for ORBIT candidacy/intensity, and an independent negative control proves unity radial_gain alone cannot promote a quiet strict frame.",
     "tools/check_multi_axis_visual_oracle.py"},
    {"PREVIEW-1", ODM_MODULE_ID_PREVIEW,
     "Preview semantics are resolved by the same canonical Render IR, Frame State and CPU reference renderer before any degradation occurs.",
     "Preview calls the reference renderer first and only then transforms the completed canonical RGBA16 frame.",
     "tests/unit/test_preview.c"},
    {"PREVIEW-2", ODM_MODULE_ID_PREVIEW,
     "Silent preview degradation changes raster density only and never timing, scene selection, seeds, Music Map or semantic event population.",
     "Frozen raster divisors 1/2/4/8 operate after canonical frame publication in scratch and retain semantics_class EXACT.",
     "tools/check_preview_oracle.py"},
    {"PREVIEW-3", ODM_MODULE_ID_PREVIEW,
     "Flat preview assets have one canonical offset order without gaps, overlaps or borrowed engine lifetime, and failed preview work publishes no partial UI frame.",
     "Exact contiguous resource/frame/pixel validation, alias rejection and staging-buffer late copy.",
     "tests/unit/test_preview.c"},
    {"PREVIEW-4", ODM_MODULE_ID_PREVIEW_FFI,
     "Preview FFI job state lives entirely in caller-owned aligned storage and stale generations cannot control a later job.",
     "Separate preview ABI publishes storage size/alignment; adapters reconstruct only generational tickets for each call.",
     "tools/check_preview_ffi.py"},
    {"PREVIEW-5", ODM_MODULE_ID_PREVIEW,
     "Cancellation and progress are monotonic and cancellation before final publication cannot leak a successful preview buffer.",
     "Underlying renderer plus per-output-row cancellation checks, job generation validation and staged output commit.",
     "tests/unit/test_preview.c"},
    {"MASTER-1", ODM_MODULE_ID_MASTER,
     "A canonical master is accepted only from a fully verified signed .odparms whose external Score recompiles byte-for-byte to the signed Render IR.",
     "Full package verification, transitive identity checks and independent Score-to-IR recompilation precede sink begin.",
     "tests/unit/test_master.c"},
    {"MASTER-2", ODM_MODULE_ID_MASTER,
     "The PCM consumed by master rendering is exactly the 48 kHz stereo Q1.31 stream bound by analysis.bin and cannot be substituted after Music Map validation.",
     "Domain-separated canonical PCM SHA-256 is compared to the validated Music Map canonical_pcm_sha256 before rendering.",
     "tests/unit/test_master.c"},
    {"MASTER-3", ODM_MODULE_ID_MASTER,
     "Master work accounting is deterministic technical output-volume work, never wall-clock time or business pricing, and observed work must equal the frozen quote.",
     "Checked pixel-frame plus audio-frame work arithmetic is bound into plan/receipt and reconciled before commit.",
     "tests/unit/test_master.c"},
    {"MASTER-4", ODM_MODULE_ID_MASTER,
     "A failed or cancelled master after sink begin never commits and never publishes a caller receipt.",
     "Transactional begin/write/commit/abort sink protocol with staged receipt publication only after successful commit.",
     "tests/unit/test_master.c"},
    {"MASTER-5", ODM_MODULE_ID_MASTER,
     "Canonical soundtrack output never truncates authored audio and every sample beyond canonical PCM through output_end_sample is exact digital silence.",
     "Audio is streamed in canonical little-endian Q1.31 stereo chunks with explicit zero fill to the exact output end.",
     "tests/unit/test_master.c"},
    {"MASTER-6", ODM_MODULE_ID_MASTER,
     "render_id binds all semantic input identities, output profile and exact timeline while excluding wall clock and delivery encoder choices.",
     "Domain-separated SHA-256 over package/Score/capability/map/policy/IR/assets/PCM plus frozen master profile and timing fields.",
     "tools/check_master_oracle.py"},
    {"MASTER-7", ODM_MODULE_ID_MASTER_CONTROLLER_SIGN,
     "Controller attestation is separated from rendering and can only verify against an externally expected public key and the exact canonical Render Receipt bytes.",
     "Ed25519 signs a domain-separated receipt message; verification checks envelope canonicality, external key, receipt hash and signature.",
     "tests/unit/test_master.c"},
    {"STUDIO-1", ODM_MODULE_ID_STUDIO_REVISION,
     "Studio package-content identity binds every verified manifest entry while remaining independent of the signing key and ZIP/signature representation.",
     "A domain-separated package content hash covers core semantic hashes plus kind/method/resource/path/size/content SHA for every signed manifest entry.",
     "tests/unit/test_studio.c"},
    {"STUDIO-2", ODM_MODULE_ID_STUDIO_REVISION,
     "A Studio revision belongs to one stable project lineage; no-op/re-sign-only children and signer substitution are rejected.",
     "Genesis derives a project_id from semantic content and signer; descendants inherit that project_id, require the same signer and a changed signer-independent content identity.",
     "tests/unit/test_studio.c"},
    {"STUDIO-3", ODM_MODULE_ID_STUDIO_REVISION,
     "Revision metadata is canonical, content-addressed and self-revalidating rather than trusting an outer record hash alone.",
     "The fixed 576-byte ODMC record recomputes revision_id from semantic fields and rejects nonzero reserved bytes or rewrapped semantic lies.",
     "tests/unit/test_studio.c"},
    {"STUDIO-4", ODM_MODULE_ID_STUDIO_WORKFLOW,
     "Revision-bound Preview cannot consume a foreign Render IR or arbitrary Music Map tick.",
     "Studio validates revision/IR/analysis identities and selects the exact 100 Hz Music Map tick from frame sample before delegating to Gate 8 Preview.",
     "tests/unit/test_studio.c"},
    {"STUDIO-5", ODM_MODULE_ID_STUDIO_APPROVAL,
     "A Preview approval binds one immutable revision to the exact Render IR, canonical frame and raster Preview pixels that were actually reviewed.",
     "A canonical approval_id covers revision identity, frame/sample geometry, raster semantics and both canonical/preview frame SHA-256 values.",
     "tests/unit/test_studio.c"},
    {"STUDIO-6", ODM_MODULE_ID_STUDIO_WORKFLOW,
     "No Studio-level revision/package mismatch can be discovered only after a master sink has begun or committed.",
     "odm_studio_master_run builds and matches the complete Gate 9 plan against the revision before delegating to odm_master_run and before sink begin.",
     "tests/unit/test_studio.c"},
    {"DELIVERY-1", ODM_MODULE_ID_DELIVERY_CONTRACT,
     "Delivery codec and encoder choices never rewrite canonical render truth; every delivery contract binds one existing Gate 9 Render Receipt.",
     "The contract imports render_id, exact timeline and Receipt SHA-256 and computes a separate domain-separated delivery_contract_id.",
     "tests/unit/test_delivery.c"},
    {"DELIVERY-2", ODM_MODULE_ID_DELIVERY_CONTRACT,
     "Delivery profile v1 is explicit and fail-closed: MP4/H.264/AAC, BT.709, yuv420p, 48 kHz, exact supported FPS and bounded even geometry.",
     "Canonical field validation plus exact samples-per-frame/frame-count relation rejects rewrapped but semantically impossible records.",
     "tests/unit/test_delivery.c"},
    {"DELIVERY-3", ODM_MODULE_ID_DELIVERY_CONTRACT,
     "Delivered bytes have their own content hash and artifact identity separate from render_id and delivery_contract_id.",
     "A fixed ODMC artifact record binds file byte count, file SHA-256 and delivery contract under a distinct hash domain.",
     "tools/check_delivery_oracle.py"},
    {"DELIVERY-4", ODM_MODULE_ID_DELIVERY_CONTRACT,
     "Wall clock, pricing, revenue, profitability and business policy cannot affect render, delivery-contract or artifact identity.",
     "Only canonical Receipt fields, versioned profile fields, encoder/settings descriptors and delivered byte identity enter the Gate 11 records.",
     "tools/check_commercial_claims.py"},
    {"DELIVERY-5", ODM_MODULE_ID_DELIVERY_CONTRACT,
     "A Delivery Artifact record proves byte identity and contract binding, not universal codec/color compliance or third-party certification.",
     "Profile conformance remains an explicitly scoped adapter observation; the artifact record contains no hidden certification bit or pricing field.",
     "tools/check_ffmpeg_delivery.py"},
    {"LAYER-1", ODM_MODULE_ID_LAYER_LAYOUT,
     "Canvas aspect, FPS and safe areas are explicit canonical configuration and cannot be inferred from UI or encoder state.",
     "Aspect equality uses checked integer ratios; safe margins are Q1.31 and resolve to one Q16.16 safe rectangle per canvas.",
     "tests/unit/test_compositor.c"},
    {"LAYER-2", ODM_MODULE_ID_BACKGROUND_LAYER,
     "Background is an independent canvas-space authority and never depends on Core mask shape or HUD metadata.",
     "Grid zoom, warp and depth consume only resolved Composition/Director values and the canvas center.",
     "tests/unit/test_compositor.c"},
    {"LAYER-3", ODM_MODULE_ID_CORE_MEDIA_LAYER,
     "Core media has one exact shape mask and fit mapping; circle, square and rounded-rect cannot silently share approximate perimeter geometry.",
     "Q16.16 SDF coverage, deterministic bilinear source sampling and explicit COVER/CONTAIN/STRETCH rules.",
     "tests/unit/test_compositor.c"},
    {"LAYER-4", ODM_MODULE_ID_REACTIVE_FIELD_LAYER,
     "Reactive field geometry follows the exact Core contour; legacy autonomous particles advance from exact 48 kHz sample coordinates, while STRICT_CAUSAL particles cannot derive motion from clock, frame rate or caller seed.",
     "Core SDF contour offset and fixed CORDIC geometry are shared; legacy uses sample-derived phase, while strict particles use fixed topology plus sector-local music amplitude for radial displacement and opacity.",
     "tools/check_strict_causal_field_oracle.py"},
    {"LAYER-5", ODM_MODULE_ID_HUD_LAYER,
     "HUD visibility and metadata never change visual music interpretation, Core geometry or Background state; progress derives only from exact sample/duration.",
     "Safe-area anchored deterministic 5x7 fallback glyphs and Q1.31 progress fill after all reactive layers.",
     "tests/unit/test_compositor.c"},
    {"LAYER-6", ODM_MODULE_ID_LAYERED_COMPOSITOR,
     "Layered output is ordered Background -> Core -> Reactive Field -> HUD and failures or cancellation before commit publish zero partial frame bytes.",
     "Caller-owned aligned scratch contains canonical working and encoded staging frames; SHA-256 and cancellation precede final memcpy publication.",
     "tests/unit/test_compositor.c"},
    {"LAYER-7", ODM_MODULE_ID_LAYER_LAYOUT,
     "A resolved frame plan and export plan are cryptographically bound to the exact layered configuration and layered policy that produced them.",
     "Fixed 1024-byte config encoding plus SHA-256 identity carried in frame/export plans; render rejects config-plan substitution.",
     "tests/unit/test_compositor.c"},
    {"LAYER-8", ODM_MODULE_ID_BACKGROUND_LAYER,
     "Perspective Grid is a canvas-space projective authority with exact horizon suppression and mirror-symmetric half-pixel geometry; it never derives projection from Core shape.",
     "One bounded integer projection scale per row, Q17 half-pixel-exact inverse projection, exact world-grid phase and an independent pixel oracle define the raster.",
     "tools/check_perspective_grid_oracle.py"},
    {"LAYER-9", ODM_MODULE_ID_LAYERED_COMPOSITOR,
     "An admitted immutable-config render is a performance optimization only and must remain byte-identical to the fully defensive public renderer.",
     "Admission performs full config validation, sizing and SHA-256 once; each frame still validates variable plan structure, admitted config identity, source surface, aliasing and cancellation.",
     "tests/unit/test_compositor.c"},
    {"LAYER-12", ODM_MODULE_ID_REACTIVE_FIELD_LAYER,
     "A held strict-causal spectrum produces held particle geometry regardless of sample, tick, ring phase or config seed; changing one spectral sector may change only deterministic geometry/opacity sourced from that sector.",
     "An independent pixel oracle reconstructs all ninety-six strict particles from the fixed topology seed, sector permutation, exact Q1.31 radius law and premultiplied blend, then adversarially perturbs external time/seed inputs and one music lane.",
     "tools/check_strict_causal_field_oracle.py"},
    {"LAYER-10", ODM_MODULE_ID_LAYER_LAYOUT,
     "Canonical convenience constructors and setters can never create a hidden render authority or partially mutate caller configuration on error.",
     "Default/aspect/core/metadata helpers transactionally materialize one ordinary validated 1024-byte Layered Config whose canonical bytes and SHA-256 remain the sole rendering authority.",
     "tests/unit/test_compositor.c"},
    {"STYLE-1", ODM_MODULE_ID_LAYERED_STYLE,
     "A Style Profile is authoring-only and can never become hidden render state beside the canonical Layered Config.",
     "Applying a canonical 512-byte Style Profile transactionally materializes one ordinary validated 1024-byte Layered Config; only that Config enters frame/export pixel authority.",
     "tools/check_style_oracle.py"},
    {"STYLE-2", ODM_MODULE_ID_LAYERED_STYLE,
     "Style layer selection cannot modify any unselected layer authority.",
     "Layer-mask application is field-scoped and unit tests require byte-identical Background/Core/Field/HUD substructures outside the selected mask.",
     "tests/unit/test_compositor.c"},
    {"LAYER-11", ODM_MODULE_ID_LAYERED_COMPOSITOR,
     "Canonical standalone Background/Core/Field/HUD outputs use the same production raster semantics as the full compositor with other layer authorities disabled.",
     "An independent Python pixel oracle reconstructs all four RGBA16LE layer buffers; integer-alpha recomposition of already-flattened buffers is explicitly not claimed associative.",
     "tools/check_layer_output_oracle.py"},
    {"LAYER-13", ODM_MODULE_ID_LAYERED_COMPOSITOR,
     "Multiscale radial morphology must preserve same-sector causal provenance through 96-native and 96-to-48 compositor paths; a final radial may never combine fast body, slow-release residue or attack from different lanes.",
     "RADIAL_PROVENANCE|RADIAL_TIMESCALE carries explicit body, release and attack arrays; release is the same-lane slow-minus-fast residue, 48-sector reduction selects one complete tuple by final radial strength, and render validation independently recomputes the multiscale final before pixel publication.",
     "tools/check_radial_provenance_oracle.py"},
    {"LAYER-14", ODM_MODULE_ID_REACTIVE_FIELD_LAYER,
     "A strict multiscale radial must raster body, release/tail and attack tip as three ordered causal zones whose extents and premultiplied alpha are derived only from that sector's preserved tuple.",
     "An independent Python oracle reconstructs the Q1.31 morphology, subpixel segment geometry, antialias coverage and RGBA16LE premultiplied blending and requires byte-identical output for the complete field buffer.",
     "tools/check_radial_timescale_geometry_oracle.py"},
    {"REACTION-1", ODM_MODULE_ID_LAYER_REACTION,
     "Every reaction route that can affect pixels is canonical Layered Config state and therefore participates in config SHA, Frame Plan and Export identity.",
     "Six packed route words occupy the former 32-byte top-level reserve; changing a route changes canonical ODMCFG14 bytes while legacy all-zero routing remains explicitly identifiable.",
     "tests/unit/test_compositor.c"},
    {"REACTION-2", ODM_MODULE_ID_LAYER_REACTION,
     "Reaction Matrix consumes only normalized outputs already resolved by Composition or Visual Director and can never reinterpret PCM, Music Map or raw media.",
     "The route source enum exposes only Composition/Director Q1.31 fields; selected non-canonical values are rejected before Frame Plan publication.",
     "tests/unit/test_compositor.c"},
    {"REACTION-3", ODM_MODULE_ID_LAYER_REACTION,
     "An all-zero legacy reaction record resolves to exactly the 0.13 default geometry while an explicit v1 default carries a distinct canonical configuration identity.",
     "Unit tests compare complete Frame Plans after masking only config_sha256 and require byte-identical legacy/explicit resolved geometry.",
     "tests/unit/test_compositor.c"},
    {"EXPORT-1", ODM_MODULE_ID_EXPORT_ENGINE,
     "Export timeline is derived from the exact layered frame count and sample clock; encoded delivery cannot silently truncate the final video frame.",
     "Frame-index to sample mapping is checked integer arithmetic and source audio is padded to output_end_sample instead of delegating duration truth to -shortest.",
     "tools/check_export_engine_oracle.py"},
    {"EXPORT-2", ODM_MODULE_ID_EXPORT_ENGINE,
     "Canonical export audio after the source soundtrack is exact stereo S32LE digital silence and never reads beyond canonical PCM.",
     "Chunk validation binds canonical PCM frame count to the Recipe and emits zero-valued Q1.31 frames through the exact output end.",
     "tests/unit/test_export_engine.c"},
    {"EXPORT-3", ODM_MODULE_ID_EXPORT_ENGINE,
     "External encoder invocation is represented as bounded NUL-separated argv tokens and never as a shell command string.",
     "All codec, geometry, FPS, color, thread, rate-control and frame-count choices are explicit Recipe/Profile fields; callers substitute only three path placeholders.",
     "tools/check_export_engine_oracle.py"},
    {"EXPORT-4", ODM_MODULE_ID_EXPORT_ENGINE,
     "FFmpeg remains a delivery adapter and cannot become canonical render truth or imply byte-identical encoded output across encoder versions.",
     "The engine binds the exact export recipe and raw inputs; local FFmpeg execution is recorded only as an adapter observation.",
     "tools/check_export_ffmpeg_smoke.py"},
    {"EXPORT-5", ODM_MODULE_ID_EXPORT_ENGINE,
     "A native export run owns exact frame-to-sample mapping and rejects Composition/Director state from any different Music tick before rendering or publication.",
     "For every frame the session derives sample from the Recipe, derives tick=floor(sample/480), and validates both provided visual states against that tick.",
     "tests/unit/test_export_run.c"},
    {"EXPORT-6", ODM_MODULE_ID_EXPORT_ENGINE,
     "Raw video/audio streams and the Export Run Receipt are transactionally bound to one Recipe; failures or cancellation never publish a successful Receipt or sink commit.",
     "Domain-separated SHA-256 covers every RGBA8/S32LE byte, sink commit occurs only after hashes/counts/cancellation checks, and abort is mandatory on post-begin failure.",
     "tools/check_export_run_smoke.py"},
    {"EXPORT-7", ODM_MODULE_ID_EXPORT_ENGINE,
     "Every Export Recipe is bound to the current canonical Export Policy; unchanged parameters cannot silently acquire different adapter, padding, argv or publication semantics.",
     "A 1024-byte Export Policy record is independently hashed and embedded in every Recipe before the domain-separated Recipe identity is computed.",
     "tools/check_export_engine_oracle.py"},
    {"EXPORT-8", ODM_MODULE_ID_EXPORT_ENGINE,
     "An admitted Native Export Session is immune to callback-side mutation of caller-owned control-plane structs.",
     "Config, Recipe, sink dispatch and Job Ticket are snapshotted before begin(); all in-flight reads use only those frozen snapshots.",
     "tests/unit/test_export_run.c"},
    {"EXPORT-9", ODM_MODULE_ID_EXPORT_ENGINE,
     "SHA-256 provider selection is a runtime-only optimization and cannot alter Export Recipe, raw stream identity or the canonical 512-byte Export Run Receipt.",
     "Accelerated OpenSSL SHA-256 is enabled only after cross-checking against the portable implementation; a forced-portable run must reproduce the same Receipt byte-for-byte.",
     "tests/unit/test_export_run.c"},
    {"EXPORT-10", ODM_MODULE_ID_EXPORT_ENGINE,
     "Every successful Export Run Receipt proves that the canonical source PCM admitted before sink begin is byte-identical to the source PCM actually transmitted, independently from the padded delivery-audio stream identity.",
     "The engine domain-hashes the complete canonical S32LE Q1.31 source before begin(), independently re-hashes only source frames during delivery, requires exact digest equality before commit, and aborts with no public Receipt on any substitution; Receipt v2 also records Export Policy and padded-audio identities.",
     "tests/unit/test_export_run.c"},
    {"EXPORT-11", ODM_MODULE_ID_EXPORT_ENGINE,
     "Direct staging and deterministic 1/2/4-row worker scheduling are runtime-only execution choices and cannot change any rendered byte or Export Run Receipt field.",
     "Workers own disjoint 64-row chunks for Background/Core/encode while Field/HUD retain canonical order; staged and copied paths are compared byte-for-byte and Receipt-for-Receipt.",
     "tests/unit/test_compositor.c"},
    {"EXPORT-12", ODM_MODULE_ID_EXPORT_ENGINE,
     "A Native Export Session has one canonical callback lifecycle and exactly one terminal outcome: successful commit or abort after any post-begin failure; no later writes or public Receipt are permitted after terminalization.",
     "Transcript tests prove begin -> all video writes -> all audio writes -> commit on success, and begin -> prefix writes -> abort on failure/cancellation; a failed commit is followed by one abort and every non-OK return leaves caller Receipt storage unchanged.",
     "tests/unit/test_export_run.c"},
    {"EXPORT-13", ODM_MODULE_ID_EXPORT_ENGINE,
     "Runtime backend recommendation is transparent, budget-bounded and non-semantic; applying the recommended direct-staging/row-worker flags cannot alter any exported byte, Recipe field or Export Run Receipt field.",
     "The public runtime planner derives only from admitted frame work and an explicit 1..4 worker budget, preserves an optional forced-portable hash choice, never enters semantic hashes, and every selectable backend is byte-parity tested against the portable copied path.",
     "tests/unit/test_export_run.c"},
    {"EXPORT-14", ODM_MODULE_ID_EXPORT_ENGINE,
     "Export profile convenience construction cannot hide adapter/color/source-format defaults or partially mutate a caller profile after invalid quality/performance input.",
     "The H.264/AAC builder materializes one ordinary validated 256-byte Profile from explicit CRF, preset, thread, bitrate and flag choices; Profile bytes/SHA remain the sole profile authority.",
     "tests/unit/test_export_engine.c"},
};

static const odm_spine_ownership odm_registry_ownership[] = {
    {"arena_storage", "odm_arena_init", "odm_arena_destroy", "not_transferable"},
    {"owner_block", "odm_owner_allocate", "odm_owner_release", "odm_owner_take"},
    {"owner_ledger", "odm_owner_init", "odm_owner_destroy", "odm_owner_move_all"},
    {"job_lifecycle", "odm_job_init", "odm_job_destroy", "caller_storage_not_transferable"},
    {"ffi_output_buffer", "caller_provided", "caller_retained", "not_transferable"},
    {"executor_allocation", "odm_executor_create", "odm_executor_destroy", "not_transferable"},
    {"png_transaction_buffer", "odm_png_decode_rgba8", "internal_free_before_return", "never_exposed"},
};

static const odm_spine_guardian odm_registry_guardians[] = {
    {"NO_WALLCLOCK_IN_RENDER_CORE", "tools/guardian.py", "src/render,src/renderer,src/score,src/ir,src/visual,src/preview,src/master,src/studio,src/delivery,src/compositor,src/export"},
    {"NO_UNSEEDED_RANDOMNESS", "tools/guardian.py", "include,src"},
    {"NO_DIRECT_AUDIO_IN_VISUAL_EFFECTS", "tools/guardian.py", "src/render,src/renderer,src/visual,src/preview,src/compositor"},
    {"NO_UI_SEMANTICS_IN_ENGINE", "tools/guardian.py", "include,src"},
    {"NO_PRESET_AS_TRUTH", "tools/guardian.py", "src/ir,src/render,src/renderer,src/visual,src/compositor"},
    {"NO_PARTIAL_MASTER", "tools/guardian.py", "src/render,src/renderer,src/master,src/studio,src/compositor,src/export"},
    {"NO_NATIVE_FLOAT_IN_CANONICAL_IR", "tools/guardian.py", "include/odm_ir*,src/ir"},
    {"NO_TIMESTAMP_BUILD_ID", "tools/guardian.py", "include/odm_version.h,src/core/version.c,tools/gen_build_meta.py"},
};

static const odm_spine_capability odm_registry_capabilities[] = {
    {"core.status", 1u, 0u, "implemented_uncertified", "tests/unit/test_status.c"},
    {"time.sample_contract", 0u, 0u, "implemented_uncertified", "tests/unit/test_time.c"},
    {"numeric.fixed_point", 0u, 0u, "implemented_uncertified", "tests/unit/test_fixed.c"},
    {"rng.deterministic", 0u, 0u, "implemented_uncertified", "tests/unit/test_rng.c"},
    {"memory.ownership", 0u, 0u, "implemented_uncertified", "tests/unit/test_memory.c"},
    {"jobs.control", 0u, 0u, "implemented_uncertified", "tests/unit/test_job.c"},
    {"music_spine", 0u, 0u, "implemented_uncertified", "tests/unit/test_spine.c"},
    {"crypto.sha256", 1u, 0u, "implemented_uncertified", "tests/unit/test_hash.c"},
    {"core.canonical_wire", 1u, 0u, "implemented_uncertified", "tests/unit/test_wire.c"},
    {"core.resource_admission", 1u, 0u, "implemented_uncertified", "tests/unit/test_limits.c"},
    {"ffi.flat_abi", 1u, 0u, "implemented_uncertified", "tests/unit/test_ffi.c"},
    {"jobs.bounded_executor", 1u, 0u, "implemented_uncertified", "tests/unit/test_executor.c"},
    {"media.probe", 1u, 0u, "implemented_uncertified", "tests/unit/test_media.c"},
    {"media.facts", 1u, 0u, "implemented_uncertified", "tests/unit/test_media.c"},
    {"media.wav_q31", 1u, 0u, "implemented_uncertified", "tests/unit/test_media.c"},
    {"media.png_rgba8", 1u, 0u, "implemented_uncertified", "tests/unit/test_media.c"},
    {"media.decode", 1u, 0u, "implemented_uncertified", "tests/unit/test_media.c"},
    {"music.resample.plan", 1u, 0u, "implemented_uncertified", "tests/unit/test_resample.c"},
    {"music.resample.q31", 1u, 0u, "implemented_uncertified", "tests/unit/test_resample.c"},
    {"music.resample.identity", 1u, 0u, "implemented_uncertified", "tests/unit/test_resample.c"},
    {"music.resample.cancel", 1u, 0u, "implemented_uncertified", "tests/unit/test_resample.c"},
    {"music.resample.duration", 1u, 0u, "implemented_uncertified", "tests/unit/test_resample.c"},
    {"music.analysis.plan", 1u, 0u, "implemented_uncertified", "tests/unit/test_music_analysis.c"},
    {"music.analysis.fft", 1u, 0u, "implemented_uncertified", "tests/unit/test_music_analysis.c"},
    {"music.analysis.features", 1u, 0u, "implemented_uncertified", "tests/unit/test_music_analysis.c"},
    {"music.analysis.map", 1u, 0u, "implemented_uncertified", "tests/unit/test_music_analysis.c"},
    {"music.analysis.policy_hash", 1u, 0u, "implemented_uncertified", "tests/unit/test_music_analysis.c"},
    {"music_reaction.high_resolution_spectrum", 1u, 0u, "implemented_uncertified", "tools/check_music_reaction_oracle.py"},
    {"music_reaction.robust_profile", 1u, 0u, "implemented_uncertified", "tools/check_music_reaction_oracle.py"},
    {"music_reaction.causal_events", 1u, 0u, "implemented_uncertified", "tests/unit/test_music_reaction.c"},
    {"music_reaction.radial_provenance", 1u, 0u, "implemented_uncertified", "tools/check_music_reaction_oracle.py"},
    {"composition.music_reaction_path", 1u, 0u, "implemented_uncertified", "tests/unit/test_music_reaction.c"},
    {"music_reaction.radial96", 1u, 0u, "implemented_uncertified", "tools/check_radial_hires_geometry_oracle.py"},
    {"music_reaction.policy_hash", 8u, 0u, "implemented_uncertified", "tools/check_music_reaction_oracle.py"},
    {"music_reaction.frequency_aware_release", 1u, 0u, "implemented_uncertified", "tools/check_music_reaction_oracle.py"},
    {"music_reaction.offline_peak_refinement", 1u, 0u, "implemented_uncertified", "tests/unit/test_music_reaction.c"},
    {"music_reaction.presentation_projection", 1u, 0u, "implemented_uncertified", "tools/check_reaction_projection_oracle.py"},
    {"music_reaction.attack_headroom", 1u, 0u, "implemented_uncertified", "tools/check_music_reaction_oracle.py"},
    {"composition.reaction_projection_path", 1u, 0u, "implemented_uncertified", "tools/check_reaction_projection_oracle.py"},
    {"music_reaction.contextual_salience", 1u, 0u, "implemented_uncertified", "tools/check_music_reaction_oracle.py"},
    {"composition.contextual_macro_authority", 1u, 0u, "implemented_uncertified", "tests/unit/test_music_reaction.c"},
    {"composition.reaction_stationary_geometry", 1u, 0u, "implemented_uncertified", "tools/check_music_reaction_oracle.py"},
    {"visual.strict_causal_policy", 1u, 0u, "implemented_uncertified", "tools/check_strict_causal_oracle.py"},
    {"visual.strict_causal_director", 1u, 0u, "implemented_uncertified", "tools/check_director_oracle.py"},
    {"layered.strict_causal_raster", 1u, 0u, "implemented_uncertified", "tools/check_strict_causal_oracle.py"},
    {"layered.strict_causal_particles", 1u, 0u, "implemented_uncertified", "tools/check_strict_causal_field_oracle.py"},
    {"visual.multi_axis_causality", 1u, 0u, "implemented_uncertified", "tools/check_multi_axis_visual_oracle.py"},
    {"visual.strict_radial_activity_authority", 1u, 0u, "implemented_uncertified", "tools/check_multi_axis_visual_oracle.py"},
    {"layered.radial_transient_provenance", 1u, 0u, "implemented_uncertified", "tools/check_radial_provenance_oracle.py"},
    {"layered.radial_multiscale_morphology", 1u, 0u, "implemented_uncertified", "tools/check_radial_timescale_geometry_oracle.py"},
    {"music_map", 1u, 0u, "implemented_uncertified", "tests/unit/test_music_map_wire.c"},
    {"music.analysis.bin", 1u, 0u, "implemented_uncertified", "tests/unit/test_music_map_wire.c"},
    {"score.schema", 1u, 0u, "implemented_uncertified", "tests/unit/test_score_ir.c"},
    {"score.capability_registry", 1u, 0u, "implemented_uncertified", "tests/unit/test_score_ir.c"},
    {"score.compile_ir", 1u, 0u, "implemented_uncertified", "tests/unit/test_score_ir.c"},
    {"render.ir.validate", 1u, 0u, "implemented_uncertified", "tests/unit/test_score_ir.c"},
    {"render.frame_state", 1u, 0u, "implemented_uncertified", "tests/unit/test_score_ir.c"},
    {"render.music_binding", 1u, 0u, "implemented_uncertified", "tests/unit/test_score_ir.c"},
    {"render.state_transfer", 1u, 0u, "implemented_uncertified", "tests/unit/test_score_ir.c"},
    {"package.odparms", 1u, 0u, "implemented_uncertified", "tests/unit/test_package.c"},
    {"package.ed25519", 1u, 0u, "implemented_uncertified", "tests/unit/test_package.c"},
    {"package.deflate", 1u, 0u, "implemented_uncertified", "tests/unit/test_package.c"},
    {"package.verify", 1u, 0u, "implemented_uncertified", "tests/unit/test_package.c"},
    {"render.reference", 1u, 0u, "implemented_uncertified", "tests/unit/test_renderer.c"},
    {"render.color.linear_bt709", 1u, 0u, "implemented_uncertified", "tests/unit/test_renderer.c"},
    {"render.sample.bilinear", 1u, 0u, "implemented_uncertified", "tests/unit/test_renderer.c"},
    {"render.video_pts", 1u, 0u, "implemented_uncertified", "tests/unit/test_renderer.c"},
    {"render.frame_root", 1u, 0u, "implemented_uncertified", "tests/unit/test_renderer.c"},
    {"visual.primary_video", 1u, 0u, "implemented_uncertified", "tests/unit/test_renderer.c"},
    {"visual.subject_video", 1u, 0u, "implemented_uncertified", "tests/unit/test_renderer.c"},
    {"visual.entry_exit", 1u, 1u, "implemented_uncertified", "tests/unit/test_visual.c"},
    {"visual.event_history", 1u, 0u, "implemented_uncertified", "tests/unit/test_visual.c"},
    {"visual.grid_proof", 1u, 0u, "implemented_uncertified", "tests/unit/test_visual.c"},
    {"visual.halo", 1u, 0u, "implemented_uncertified", "tests/unit/test_visual.c"},
    {"visual.residual_event_field", 1u, 0u, "implemented_uncertified", "tests/unit/test_visual.c"},
    {"visual.deterministic_particles", 1u, 0u, "implemented_uncertified", "tests/unit/test_visual.c"},
    {"visual.composition_profiled", 1u, 0u, "implemented_uncertified", "tools/check_composition_oracle.py"},
    {"visual.director_macro", 1u, 0u, "implemented_uncertified", "tools/check_director_oracle.py"},
    {"visual.policy_hash", 7u, 0u, "implemented_uncertified", "tools/check_visual_policy_oracle.py"},
    {"preview.raster_exact_semantics", 1u, 0u, "implemented_uncertified", "tools/check_preview_oracle.py"},
    {"preview.raster_degradation", 1u, 0u, "implemented_uncertified", "tests/unit/test_preview.c"},
    {"ffi.preview_abi", 1u, 0u, "implemented_uncertified", "tools/check_preview_ffi.py"},
    {"ffi.preview_job_control", 1u, 0u, "implemented_uncertified", "tests/unit/test_preview.c"},
    {"package.verified_core_views", 1u, 0u, "implemented_uncertified", "tests/unit/test_master.c"},
    {"music_map.validated_view", 1u, 0u, "implemented_uncertified", "tests/unit/test_master.c"},
    {"master.plan", 1u, 0u, "implemented_uncertified", "tests/unit/test_master.c"},
    {"master.reference", 1u, 0u, "implemented_uncertified", "tests/unit/test_master.c"},
    {"master.canonical_soundtrack", 1u, 0u, "implemented_uncertified", "tools/check_master_oracle.py"},
    {"master.render_id", 1u, 0u, "implemented_uncertified", "tools/check_master_oracle.py"},
    {"receipt.render", 1u, 0u, "implemented_uncertified", "tools/check_master_oracle.py"},
    {"receipt.controller_signature", 1u, 0u, "implemented_uncertified", "tests/unit/test_master.c"},
    {"package.content_identity", 1u, 0u, "implemented_uncertified", "tests/unit/test_studio.c"},
    {"studio.revision", 1u, 0u, "implemented_uncertified", "tests/unit/test_studio.c"},
    {"studio.project_lineage", 1u, 0u, "implemented_uncertified", "tests/unit/test_studio.c"},
    {"studio.preview_revision", 1u, 0u, "implemented_uncertified", "tests/unit/test_studio.c"},
    {"studio.preview_approval", 1u, 0u, "implemented_uncertified", "tests/unit/test_studio.c"},
    {"studio.master_revision", 1u, 0u, "implemented_uncertified", "tests/unit/test_studio.c"},
    {"delivery.contract", 1u, 0u, "implemented_uncertified", "tests/unit/test_delivery.c"},
    {"delivery.mp4_h264_aac_profile", 1u, 0u, "observed_local_adapter_only", "tools/check_ffmpeg_delivery.py"},
    {"delivery.artifact_identity", 1u, 0u, "implemented_uncertified", "tools/check_delivery_oracle.py"},
    {"compositor.canvas_aspect", 1u, 0u, "implemented_uncertified", "tests/unit/test_compositor.c"},
    {"compositor.background_grid", 1u, 0u, "implemented_uncertified", "tests/unit/test_compositor.c"},
    {"compositor.background_perspective_grid", 1u, 0u, "implemented_uncertified", "tools/check_perspective_grid_oracle.py"},
    {"compositor.core_mask", 1u, 0u, "implemented_uncertified", "tests/unit/test_compositor.c"},
    {"compositor.reactive_field", 1u, 0u, "implemented_uncertified", "tests/unit/test_compositor.c"},
    {"compositor.hud", 1u, 0u, "implemented_uncertified", "tests/unit/test_compositor.c"},
    {"compositor.config_identity", 1u, 0u, "implemented_uncertified", "tests/unit/test_compositor.c"},
    {"compositor.transactional_render", 1u, 0u, "implemented_uncertified", "tests/unit/test_compositor.c"},
    {"compositor.admitted_render_identity", 1u, 0u, "implemented_uncertified", "tests/unit/test_compositor.c"},
    {"compositor.canonical_config_builder", 1u, 0u, "implemented_uncertified", "tests/unit/test_compositor.c"},
    {"compositor.style_profile", 1u, 0u, "implemented_uncertified", "tools/check_style_oracle.py"},
    {"compositor.layer_outputs", 1u, 0u, "implemented_uncertified", "tools/check_layer_output_oracle.py"},
    {"compositor.reaction_matrix", 1u, 0u, "implemented_uncertified", "tools/check_reaction_oracle.py"},
    {"compositor.reaction_band_routing", 1u, 0u, "implemented_uncertified", "tools/check_reaction_oracle.py"},
    {"export.recipe_identity", 1u, 0u, "implemented_uncertified", "tools/check_export_engine_oracle.py"},
    {"export.exact_timeline", 1u, 0u, "implemented_uncertified", "tests/unit/test_export_engine.c"},
    {"export.padded_pcm", 1u, 0u, "implemented_uncertified", "tools/check_export_engine_oracle.py"},
    {"export.ffmpeg_argv", 1u, 0u, "observed_local_adapter_only", "tools/check_export_ffmpeg_smoke.py"},
    {"export.native_session", 1u, 0u, "implemented_uncertified", "tests/unit/test_export_run.c"},
    {"export.run_receipt", 1u, 0u, "implemented_uncertified", "tools/check_export_run_smoke.py"},
    {"export.policy_identity", 1u, 0u, "implemented_uncertified", "tools/check_export_engine_oracle.py"},
    {"export.argv_binding", 1u, 0u, "observed_local_adapter_only", "tools/check_export_ffmpeg_smoke.py"},
    {"export.hash_provider_parity", 1u, 0u, "implemented_uncertified", "tests/unit/test_export_run.c"},
    {"export.source_pcm_identity", 3u, 0u, "implemented_uncertified", "tests/unit/test_export_run.c"},
    {"export.session_transcript", 1u, 0u, "implemented_uncertified", "tests/unit/test_export_run.c"},
    {"export.render_runtime_parity", 1u, 0u, "implemented_uncertified", "tests/unit/test_export_run.c"},
    {"export.runtime_recommendation", 1u, 0u, "implemented_uncertified", "tests/unit/test_export_run.c"},
    {"export.profile_builder", 1u, 0u, "implemented_uncertified", "tests/unit/test_export_engine.c"},
};

/* These registries are intentionally empty before their owning gates.  Their explicit presence
 * prevents an absent subsystem from being mistaken for an implemented one. */

static const odm_spine_state_model odm_registry_state_models[] = {
    {"visual.black_void", "STATELESS", "tests/unit/test_score_ir.c"},
    {"visual.primary_empty", "STATELESS", "tests/unit/test_score_ir.c"},
    {"visual.primary_image", "STATELESS", "tests/unit/test_score_ir.c"},
    {"visual.subject_image", "STATELESS", "tests/unit/test_score_ir.c"},
    {"visual.look_identity", "STATELESS", "tests/unit/test_score_ir.c"},
    {"visual.primary_video", "STATELESS", "tests/unit/test_renderer.c"},
    {"visual.subject_video", "STATELESS", "tests/unit/test_renderer.c"},
    {"visual.grid_proof", "STATELESS", "tests/unit/test_visual.c"},
    {"visual.halo", "STATELESS", "tests/unit/test_visual.c"},
    {"visual.residual_event_field", "EVENT_HISTORY", "tests/unit/test_visual.c"},
    {"visual.deterministic_particles", "EVENT_HISTORY", "tests/unit/test_visual.c"},
};

static const odm_spine_backend odm_registry_renderer_backends[] = {
    {"cpu_reference_v1", "implemented_uncertified", "tests/unit/test_renderer.c"},
};

static const odm_spine_backend odm_registry_output_profiles[] = {
    {"master.reference_rgba16_pcm_q31_v1", "implemented_uncertified", "tools/check_master_oracle.py"},
    {"delivery.mp4_h264_aac_sdr_bt709_v1", "observed_local_adapter_only", "tools/check_ffmpeg_delivery.py"},
};

static const odm_spine_parity odm_registry_parity_contracts[] = {
    {"preview.cpu_reference_semantics",
     "Canonical CPU reference frame before preview raster conversion",
     "Preview frame generated from that canonical frame with raster-only degradation",
     "implemented_uncertified", "tools/check_preview_oracle.py"},
};

static const odm_spine_backend odm_registry_media_adapters[] = {
    {"wav.pcm", "implemented_uncertified", "tests/unit/test_media.c"},
    {"png.rgba8", "implemented_uncertified", "tests/unit/test_media.c"},
    {"flac", "recognized_only", "adapter_not_linked"},
    {"jpeg", "recognized_only", "adapter_not_linked"},
    {"webp", "recognized_only", "adapter_not_linked"},
    {"mp3", "recognized_only", "adapter_not_linked"},
    {"isobmff", "recognized_only", "libav_headers_unavailable"},
    {"webm", "recognized_only", "libav_headers_unavailable"},
};

static const odm_spine_investigation odm_registry_investigations[] = {
    {"SEC-G0-GUARDIANS", "Architectural dependency and semantic-boundary regressions",
     "regression_covered_not_audit_complete", "tests/guardians/fixtures"},
    {"SEC-G0-MEMORY", "Bounds, overflow, OOM rollback and ownership lifecycle",
     "regression_covered_not_audit_complete", "tests/unit/test_memory.c"},
    {"SEC-G0-JOBS", "Cancellation publication and stale-generation rejection",
     "regression_covered_not_audit_complete", "tests/unit/test_job.c"},
    {"SEC-G1-WIRE", "Canonical decoding, truncation, hostile lengths and content integrity",
     "regression_covered_not_audit_complete", "tests/unit/test_wire.c"},
    {"SEC-G1-ABI", "FFI size negotiation, fixed layout and non-publication on failure",
     "regression_covered_not_audit_complete", "tests/unit/test_ffi.c"},
    {"SEC-G1-EXECUTOR", "Queue bounds, cancellation, shutdown, stale handles and concurrent accounting",
     "regression_covered_not_audit_complete", "tests/unit/test_executor.c"},
    {"SEC-G2-WAV", "Hostile RIFF chunk sizes, format contradictions, truncation and unsupported encodings",
     "regression_covered_not_audit_complete", "tests/unit/test_media.c"},
    {"SEC-G2-PCM", "Integer/IEEE sample conversion, saturation and canonical byte identity",
     "regression_covered_not_audit_complete", "tests/unit/test_media.c"},
    {"SEC-G2-PNG", "PNG chunk bounds, CRC integrity, dimensions and transactional decode",
     "regression_covered_not_audit_complete", "tests/unit/test_media.c"},
    {"SEC-G2-DISPATCH", "Signature confusion, unsupported-format promotion and error provenance",
     "regression_covered_not_audit_complete", "tests/unit/test_media.c"},
    {"SEC-G3-RESAMPLE-NUMERIC", "Fixed-point coefficient generation, accumulator bounds, signed rounding and Q1.31 saturation",
     "regression_covered_not_audit_complete", "tests/unit/test_resample.c"},
    {"SEC-G3-RESAMPLE-ALIAS", "Downsampling cutoff, bounded Lanczos support and canonical phase selection",
     "regression_covered_not_audit_complete", "tests/unit/test_resample.c"},
    {"SEC-G3-RESAMPLE-PLAN", "Coefficient-table mutation, plan/version mismatch and content identity",
     "regression_covered_not_audit_complete", "tests/unit/test_resample.c"},
    {"SEC-G3-RESAMPLE-CANCEL", "Cancellation before publication and bounded periodic cancellation polling",
     "regression_covered_not_audit_complete", "tests/unit/test_resample.c"},
    {"SEC-G3-ANALYSIS-NUMERIC", "FFT fixed-point scaling, spectral accumulation, RMS square roots and integer rounding",
     "regression_covered_not_audit_complete", "tests/unit/test_music_analysis.c"},
    {"SEC-G3-ANALYSIS-STATE", "Sequential flux/envelope state, zero-padding boundaries and transactional tick publication",
     "regression_covered_not_audit_complete", "tests/unit/test_music_analysis.c"},
    {"SEC-G3-POLICY", "Canonical policy serialization, table mutation and SHA-256 identity drift",
     "regression_covered_not_audit_complete", "tests/unit/test_music_analysis.c"},
    {"SEC-G3-INFERENCE-BOUNDARY", "Exact signal facts separated from onset/beat/BPM/phrase/section semantic inference",
     "regression_covered_not_audit_complete", "tests/unit/test_music_analysis.c"},
    {"SEC-G3-REACTION-LOCALITY", "Spectral aliasing, outlier-dominated normalization, non-causal event thresholds, autonomous reaction phase and hi-res radial geometry loss",
     "regression_covered_not_audit_complete", "tools/check_music_reaction_oracle.py"},
    {"SEC-G3-REACTION-PROJECTION", "Video-rate temporal aliasing, future evidence leakage, duplicated source ticks, seek replay or unbounded presentation-interval scans",
     "regression_covered_not_audit_complete", "tools/check_reaction_projection_oracle.py"},
    {"SEC-G3-REACTION-SALIENCE", "Track-context salience overwriting raw evidence, silence/sustain controlling normalization, mixed stream semantics or contextual macro authority leaking into local spectral geometry",
     "regression_covered_not_audit_complete", "tools/check_music_reaction_oracle.py"},
    {"SEC-G3-ANALYSIS-WIRE", "analysis.bin size arithmetic, integrity, schema confusion and transactional decode",
     "regression_covered_not_audit_complete", "tests/unit/test_music_map_wire.c"},
    {"SEC-G4-SCORE", "Hostile Score counts, identifier ordering, topology, capability confusion and reserved fields",
     "regression_covered_not_audit_complete", "tests/unit/test_score_ir.c"},
    {"SEC-G4-IR-WIRE", "Render IR size arithmetic, section confusion, truncation, semantic re-signing and digest integrity",
     "regression_covered_not_audit_complete", "tests/unit/test_score_ir.c"},
    {"SEC-G4-FRAME", "Frame-index overflow, invalid Music Map tick binding and transactional frame publication",
     "regression_covered_not_audit_complete", "tests/unit/test_score_ir.c"},
    {"SEC-G4-CAPABILITY", "Unknown capability/version/state/resource combinations and capability-hash drift",
     "regression_covered_not_audit_complete", "tests/unit/test_score_ir.c"},
    {"SEC-G4-AUTOMATION", "Automation interval ambiguity, fixed-point interpolation overflow and modulation saturation",
     "regression_covered_not_audit_complete", "tests/unit/test_score_ir.c"},
    {"SEC-G5-ZIP", "ZIP path traversal, duplicate names, local/central disagreement, overlap, gaps, Zip64, extras and data descriptors",
     "regression_covered_not_audit_complete", "tests/unit/test_package.c"},
    {"SEC-G5-DEFLATE", "Compressed-data truncation, invalid distance/length symbols, expansion bombs and noncanonical DEFLATE block types",
     "regression_covered_not_audit_complete", "tests/unit/test_package.c"},
    {"SEC-G5-SIGNATURE", "Manifest mutation, signature mutation, embedded-key substitution and expected-key mismatch",
     "regression_covered_not_audit_complete", "tests/unit/test_package.c"},
    {"SEC-G5-IDENTITY", "Transitive Score/IR/Music Map/Music Policy identity mismatch and semantic re-signing",
     "regression_covered_not_audit_complete", "tests/unit/test_package.c"},
    {"SEC-G5-PUBLICATION", "Insufficient buffers and late integrity failures publishing partial package or extraction data",
     "regression_covered_not_audit_complete", "tests/unit/test_package.c"},
    {"SEC-G6-COLOR", "Transfer-function table integrity, fixed-point color rounding, alpha premultiplication and source-over saturation",
     "regression_covered_not_audit_complete", "tests/unit/test_renderer.c"},
    {"SEC-G6-TRANSFORM", "Q32.32 transform overflow, CORDIC quadrant boundaries, inverse scaling and out-of-bounds texture coordinates",
     "regression_covered_not_audit_complete", "tests/unit/test_renderer.c"},
    {"SEC-G6-ASSET", "Resource identity confusion, malformed surface metadata, dimensions, byte extents and asset ordering",
     "regression_covered_not_audit_complete", "tests/unit/test_renderer.c"},
    {"SEC-G6-VIDEO", "Video interval gaps, overlap, local-sample underflow and deterministic PTS-frame selection",
     "regression_covered_not_audit_complete", "tests/unit/test_renderer.c"},
    {"SEC-G6-COMPOSITE", "Premultiplied blend ordering, scene isolation and transition interpolation independent of node count",
     "regression_covered_not_audit_complete", "tests/unit/test_renderer.c"},
    {"SEC-G6-PUBLICATION", "Frame/scratch capacity, scratch alignment, cancellation and non-publication on late failure",
     "regression_covered_not_audit_complete", "tests/unit/test_renderer.c"},
    {"SEC-G6-ROOT", "Frame hash domain separation, sequence substitution/reordering and premature or repeated root finalization",
     "regression_covered_not_audit_complete", "tests/unit/test_renderer.c"},
    {"SEC-G7-STATE-SLOT", "State-slot confusion, missing destination state and unauthorized COPY ancestry",
     "regression_covered_not_audit_complete", "tests/unit/test_visual.c"},
    {"SEC-G7-HISTORY", "Visual Memory cycles, transfer-depth exhaustion, RESET boundary leaks and latest-event eviction",
     "regression_covered_not_audit_complete", "tests/unit/test_visual.c"},
    {"SEC-G7-SEED", "Unseeded or cross-domain procedural randomness and cue-identity collisions",
     "regression_covered_not_audit_complete", "tests/unit/test_visual.c"},
    {"SEC-G7-PROCEDURAL", "Procedural coordinate overflow, alpha/channel bounds and non-deterministic raster state",
     "regression_covered_not_audit_complete", "tests/unit/test_visual.c"},
    {"SEC-G7-PUBLICATION", "Entry/Exit, Visual Memory or procedural failures leaking partial reference frames",
     "regression_covered_not_audit_complete", "tests/unit/test_visual.c"},
    {"SEC-G8-RASTER", "Raster degradation altering canonical timing or semantic state instead of presentation density",
     "regression_covered_not_audit_complete", "tools/check_preview_oracle.py"},
    {"SEC-G8-FLAT-ASSETS", "Hostile FFI offsets, gaps, overlaps, counts and resource/frame identity confusion",
     "regression_covered_not_audit_complete", "tests/unit/test_preview.c"},
    {"SEC-G8-ALIAS", "FFI scratch/output aliasing with immutable input or asset buffers causing undefined behavior or self-corruption",
     "regression_covered_not_audit_complete", "tests/unit/test_preview.c"},
    {"SEC-G8-JOB", "Misaligned caller storage, stale generations, cancellation races and non-monotonic progress publication",
     "regression_covered_not_audit_complete", "tools/check_preview_ffi.py"},
    {"SEC-G8-ABI", "Base ABI drift, preview struct-layout drift and shared-library symbol/lifecycle mismatch",
     "regression_covered_not_audit_complete", "tools/check_preview_ffi.py"},
    {"SEC-G9-PROJECT", "Signed-package substitution, Score/IR disagreement and transitive identity mismatch before master execution",
     "regression_covered_not_audit_complete", "tests/unit/test_master.c"},
    {"SEC-G9-PCM", "Canonical PCM substitution, length mismatch, soundtrack truncation and non-zero post-audio padding",
     "regression_covered_not_audit_complete", "tools/check_master_oracle.py"},
    {"SEC-G9-WORK", "Overflow, under-accounting and quote/observed disagreement in deterministic master work units",
     "regression_covered_not_audit_complete", "tests/unit/test_master.c"},
    {"SEC-G9-SINK", "Partial output publication, commit after failure and missing abort after transactional begin",
     "regression_covered_not_audit_complete", "tests/unit/test_master.c"},
    {"SEC-G9-RECEIPT", "Render Receipt truncation, reserved-field mutation, render_id substitution and observed-work forgery",
     "regression_covered_not_audit_complete", "tools/check_master_oracle.py"},
    {"SEC-G9-SIGNING", "Controller-key substitution, receipt substitution and signature-envelope ambiguity",
     "regression_covered_not_audit_complete", "tests/unit/test_master.c"},
    {"SEC-G10-CONTENT", "Signed package DATA/MEDIA substitution hidden behind unchanged Score/IR identities or signer-only changes",
     "regression_covered_not_audit_complete", "tests/unit/test_studio.c"},
    {"SEC-G10-LINEAGE", "Unrelated-parent grafting, project-id drift, signer rotation and no-op revision inflation",
     "regression_covered_not_audit_complete", "tests/unit/test_studio.c"},
    {"SEC-G10-REVISION", "Rewrapped revision semantic forgery, reserved-field ambiguity and revision-id mismatch",
     "regression_covered_not_audit_complete", "tests/unit/test_studio.c"},
    {"SEC-G10-PREVIEW", "Foreign analysis.bin, Render IR or arbitrary Music Map tick substituted into a revision Preview",
     "regression_covered_not_audit_complete", "tests/unit/test_studio.c"},
    {"SEC-G10-APPROVAL", "Approval replay across revision/frame/raster or canonical-versus-preview hash substitution",
     "regression_covered_not_audit_complete", "tests/unit/test_studio.c"},
    {"SEC-G10-MASTER", "Stale revision/package execution or Studio-level mismatch discovered after sink begin/commit",
     "regression_covered_not_audit_complete", "tests/unit/test_studio.c"},
    {"SEC-G11-CONTRACT", "Receipt substitution, encoder/settings ambiguity, impossible geometry/timeline and delivery-id forgery",
     "regression_covered_not_audit_complete", "tests/unit/test_delivery.c"},
    {"SEC-G11-ARTIFACT", "Delivered-byte substitution, byte-count ambiguity and artifact-id forgery",
     "regression_covered_not_audit_complete", "tools/check_delivery_oracle.py"},
    {"SEC-G11-ADAPTER", "Local codec capability drift, color-profile mismatch and accidental promotion of host observation into universal certification",
     "regression_covered_not_audit_complete", "tools/check_ffmpeg_delivery.py"},
    {"SEC-G11-CONFORMANCE", "Treating a content-addressed delivered file as proof that its encoded samples universally conform to the declared delivery profile",
     "regression_covered_not_audit_complete", "tools/check_commercial_claims.py"},
    {"SEC-E1-COMPOSITION", "Feature normalization, tick continuity, Q1.31 saturation and transactional composition publication",
     "regression_covered_not_audit_complete", "tools/check_composition_oracle.py"},
    {"SEC-E1-DIRECTOR", "Macro-layout thrash, transition overflow, stale tick order and partial Director publication",
     "regression_covered_not_audit_complete", "tools/check_director_oracle.py"},
    {"SEC-E1-STRICT-CAUSAL", "Seed, wall/project time, procedural phase or orbit authority masquerading as music-caused geometry in the strict reaction path",
     "regression_covered_not_audit_complete", "tools/check_strict_causal_oracle.py"},
    {"SEC-E1-MULTI-AXIS", "Transfer gain, isolated spectral energy or moderate salience escalating into unrelated global visual axes or structural layout changes",
     "regression_covered_not_audit_complete", "tools/check_multi_axis_visual_oracle.py"},
    {"SEC-E1-VISUAL-POLICY", "Semantic drift between persisted visual state and the Composition/Director thresholds or layout targets that produced it",
     "regression_covered_not_audit_complete", "tools/check_visual_policy_oracle.py"},
    {"SEC-E2-GEOMETRY", "Aspect, safe-area, Q16.16 SDF or Core-contour arithmetic causing asymmetric or out-of-range geometry",
     "regression_covered_not_audit_complete", "tests/unit/test_compositor.c"},
    {"SEC-E2-PERSPECTIVE", "Perspective-grid singularity, sub-pixel horizon aliasing or signed projection rounding causing asymmetric or unbounded background geometry",
     "regression_covered_not_audit_complete", "tools/check_perspective_grid_oracle.py"},
    {"SEC-E2-ALIAS", "Layer scratch/output aliasing configuration, frame plan or source pixels and corrupting immutable inputs",
     "regression_covered_not_audit_complete", "tests/unit/test_compositor.c"},
    {"SEC-E2-PUBLICATION", "Late layer, hash or cancellation failure leaking a partial composed frame",
     "regression_covered_not_audit_complete", "tests/unit/test_compositor.c"},
    {"SEC-E2-IDENTITY", "Substituting a different HUD/Core/Background configuration under an otherwise valid resolved frame plan",
     "regression_covered_not_audit_complete", "tests/unit/test_compositor.c"},
    {"SEC-E2-TIME", "Particle or HUD time behavior changing with export FPS instead of exact sample time",
     "regression_covered_not_audit_complete", "tests/unit/test_compositor.c"},
    {"SEC-E2-ADMISSION", "Admitted render bypassing immutable config identity, per-frame structural checks or diverging byte output from the public defensive renderer",
     "regression_covered_not_audit_complete", "tests/unit/test_compositor.c"},
    {"SEC-E2-CONFIG-BUILDER", "Convenience constructors or setters creating invalid hidden defaults, partial mutation on failure, or output not represented by canonical Layered Config bytes",
     "regression_covered_not_audit_complete", "tests/unit/test_compositor.c"},
    {"SEC-E2-STYLE", "Style profile drift, hidden authoring state, layer-mask spillover or malformed canonical style serialization",
     "regression_covered_not_audit_complete", "tools/check_style_oracle.py"},
    {"SEC-E2-LAYER-OUTPUT", "Standalone layer raster divergence, transparent-background contamination or false flattened-alpha associativity assumptions",
     "regression_covered_not_audit_complete", "tools/check_layer_output_oracle.py"},
    {"SEC-E2-REACTION", "Malformed route bits, ambiguous binary NONE sources, non-Q1.31 selected signals, hidden routing outside config identity or legacy-default drift",
     "regression_covered_not_audit_complete", "tools/check_reaction_oracle.py"},
    {"SEC-E2-RADIAL-PROVENANCE", "Cross-lane mixing of fast body, slow-release residue or transient attack; forged multiscale finals; or stale provenance surviving 96-to-48 reduction and reaching the raster",
     "regression_covered_not_audit_complete", "tools/check_radial_provenance_oracle.py"},
    {"SEC-E2-RADIAL-TIMESCALE-RASTER", "Correct multiscale values being published into the wrong radial zone, with wrong subpixel extent, opacity, antialias coverage or premultiplied blend",
     "regression_covered_not_audit_complete", "tools/check_radial_timescale_geometry_oracle.py"},
    {"SEC-E3-EXPORT-TIMELINE", "Export integer overflow, frame/sample disagreement, last-frame truncation and audio padding mismatch",
     "regression_covered_not_audit_complete", "tests/unit/test_export_engine.c"},
    {"SEC-E3-EXPORT-ARGV", "Shell injection, token overflow, hidden encoder flags and path quoting ambiguity at the external adapter boundary",
     "regression_covered_not_audit_complete", "tools/check_export_engine_oracle.py"},
    {"SEC-E3-EXPORT-DRIFT", "External encoder/version/color behavior being misrepresented as canonical engine truth or universal certification",
     "regression_covered_not_audit_complete", "tools/check_export_ffmpeg_smoke.py"},
    {"SEC-E3-EXPORT-STATE", "Core/state providers returning a frame from the wrong sample or Music tick and silently desynchronizing the composed video",
     "regression_covered_not_audit_complete", "tests/unit/test_export_run.c"},
    {"SEC-E3-EXPORT-COMMIT", "A partial raw stream, late cancellation or sink failure being represented as a successful export run",
     "regression_covered_not_audit_complete", "tools/check_export_run_smoke.py"},
    {"SEC-E3-EXPORT-HASH-PROVIDER", "An accelerated cryptographic backend drifting from portable SHA-256 or changing export identity",
     "regression_covered_not_audit_complete", "tests/unit/test_export_run.c"},
    {"SEC-E3-EXPORT-POLICY", "Export semantics changing while a Recipe appears to preserve the same identity",
     "regression_covered_not_audit_complete", "tools/check_export_engine_oracle.py"},
    {"SEC-E3-EXPORT-CALLBACK-MUTATION", "Host callbacks mutating admitted config, recipe, sink or job control during an active export session",
     "regression_covered_not_audit_complete", "tests/unit/test_export_run.c"},
    {"SEC-E3-EXPORT-PCM-IDENTITY", "Canonical source PCM being mutated after admission, substituted during delivery, hidden by padding or conflated with the final padded delivery-audio stream identity",
     "regression_covered_not_audit_complete", "tests/unit/test_export_run.c"},
    {"SEC-E3-EXPORT-SESSION-ORDER", "Callback reordering, double terminalization, writes after commit/abort, failed commit without abort, or public Receipt publication after any non-OK session outcome",
     "regression_covered_not_audit_complete", "tests/unit/test_export_run.c"},
    {"SEC-E3-EXPORT-RUNTIME", "Row-worker data races, staging lifetime misuse or runtime scheduling changing canonical output",
     "regression_covered_not_audit_complete", "tests/unit/test_export_run.c"},
    {"SEC-E3-EXPORT-RECOMMENDATION", "A runtime recommendation exceeding the host worker budget, enabling mutually exclusive backends, becoming hidden semantic authority, or changing canonical output",
     "regression_covered_not_audit_complete", "tests/unit/test_export_run.c"},
    {"SEC-E3-EXPORT-PROFILE-BUILDER", "Convenience profile construction hiding encoder/color/source defaults, accepting invalid quality knobs, or partially mutating caller state on failure",
     "regression_covered_not_audit_complete", "tests/unit/test_export_engine.c"},
};

const odm_spine_module *odm_spine_modules(size_t *out_count) {
    if (out_count) *out_count = sizeof(odm_registry_modules) /
                                sizeof(odm_registry_modules[0]);
    return odm_registry_modules;
}

const odm_spine_dependency *odm_spine_dependencies(size_t *out_count) {
    if (out_count) *out_count = sizeof(odm_registry_dependencies) /
                                sizeof(odm_registry_dependencies[0]);
    return odm_registry_dependencies;
}

const odm_spine_invariant *odm_spine_invariants(size_t *out_count) {
    if (out_count) *out_count = sizeof(odm_registry_invariants) /
                                sizeof(odm_registry_invariants[0]);
    return odm_registry_invariants;
}

const odm_spine_ownership *odm_spine_ownerships(size_t *out_count) {
    if (out_count) *out_count = sizeof(odm_registry_ownership) /
                                sizeof(odm_registry_ownership[0]);
    return odm_registry_ownership;
}

const odm_spine_guardian *odm_spine_guardians(size_t *out_count) {
    if (out_count) *out_count = sizeof(odm_registry_guardians) /
                                sizeof(odm_registry_guardians[0]);
    return odm_registry_guardians;
}

const odm_spine_capability *odm_spine_capabilities(size_t *out_count) {
    if (out_count) *out_count = sizeof(odm_registry_capabilities) /
                                sizeof(odm_registry_capabilities[0]);
    return odm_registry_capabilities;
}

const odm_spine_state_model *odm_spine_state_models(size_t *out_count) {
    if (out_count) *out_count = sizeof(odm_registry_state_models) /
                                sizeof(odm_registry_state_models[0]);
    return odm_registry_state_models;
}

const odm_spine_backend *odm_spine_renderer_backends(size_t *out_count) {
    if (out_count) *out_count = sizeof(odm_registry_renderer_backends) /
                                sizeof(odm_registry_renderer_backends[0]);
    return odm_registry_renderer_backends;
}

const odm_spine_backend *odm_spine_media_adapters(size_t *out_count) {
    if (out_count) *out_count = sizeof(odm_registry_media_adapters) /
                                sizeof(odm_registry_media_adapters[0]);
    return odm_registry_media_adapters;
}

const odm_spine_backend *odm_spine_output_profiles(size_t *out_count) {
    if (out_count) *out_count = sizeof(odm_registry_output_profiles) /
                                sizeof(odm_registry_output_profiles[0]);
    return odm_registry_output_profiles;
}

const odm_spine_parity *odm_spine_parity_contracts(size_t *out_count) {
    if (out_count) *out_count = sizeof(odm_registry_parity_contracts) /
                                sizeof(odm_registry_parity_contracts[0]);
    return odm_registry_parity_contracts;
}

const odm_spine_bug *odm_spine_known_bugs(size_t *out_count) {
    if (out_count) *out_count = 0u;
    return NULL;
}

const odm_spine_investigation *odm_spine_security_investigations(
    size_t *out_count) {
    if (out_count) {
        *out_count = sizeof(odm_registry_investigations) /
                     sizeof(odm_registry_investigations[0]);
    }
    return odm_registry_investigations;
}

uint32_t odm_spine_registry_source_file_count(void) {
    return ODM_INVENTORY_SOURCE_FILE_COUNT;
}

uint32_t odm_spine_registry_source_line_count(void) {
    return ODM_INVENTORY_SOURCE_LINE_COUNT;
}
