#include "odm_export.h"
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

typedef struct { uint8_t px[64]; } provider_ctx;
typedef struct {
    FILE *v,*a;
    char stage_dir[512], final_dir[512], vp[512], ap[512], rp[512];
    int active;
} file_sink;
static uint32_t q(uint32_t n,uint32_t d){return (uint32_t)(((uint64_t)INT32_MAX*n+d/2u)/d);}
static void cfg(odm_layered_config*c){memset(c,0,sizeof(*c));c->schema_version=1;c->canvas.schema_version=1;c->canvas.aspect=ODM_CANVAS_ASPECT_SQUARE_1_1;c->canvas.width=32;c->canvas.height=32;c->canvas.fps=30;c->background.schema_version=1;c->background.style=ODM_BACKGROUND_GRID;c->background.solid_color.a=65535;c->background.grid_color.r=65535;c->background.grid_color.g=65535;c->background.grid_color.b=65535;c->background.grid_color.a=65535;c->background.grid_spacing_q16=8u<<16;c->background.grid_line_q16=1u<<16;c->background.grid_feather_q16=1u<<16;c->background.opacity_q31=INT32_MAX;c->core.schema_version=1;c->core.shape=ODM_CORE_SHAPE_CIRCLE;c->core.fit=ODM_CORE_FIT_COVER;c->core.center_x_q31=q(1,2);c->core.center_y_q31=q(1,2);c->core.width_q31=q(1,2);c->core.height_q31=q(1,2);c->core.feather_q16=1u<<16;c->core.opacity_q31=INT32_MAX;c->field.schema_version=1;c->field.flags=ODM_FIELD_RADIAL_BARS|ODM_FIELD_PARTICLES;c->field.radial_segments=48;c->field.particle_count=12;c->field.ring_gap_q16=2u<<16;c->field.bar_min_q16=1u<<16;c->field.bar_max_q16=4u<<16;c->field.bar_width_q16=1u<<16;c->field.particle_radius_q16=1u<<16;c->field.field_opacity_q31=INT32_MAX;c->field.primary_color.r=65535;c->field.primary_color.g=65535;c->field.primary_color.b=65535;c->field.primary_color.a=65535;c->field.seed=9;c->hud.schema_version=1;c->hud.flags=ODM_HUD_PROGRESS_BAR;c->hud.margin_q16=2u<<16;c->hud.progress_height_q16=1u<<16;c->hud.progress_width_q31=q(3,4);c->hud.text_scale_q16=1u<<16;c->hud.opacity_q31=INT32_MAX;c->hud.foreground_color.r=65535;c->hud.foreground_color.g=65535;c->hud.foreground_color.b=65535;c->hud.foreground_color.a=65535;}
static void prof(odm_export_profile*p){memset(p,0,sizeof(*p));p->schema_version=1;p->adapter=1;p->container=1;p->video_codec=1;p->audio_codec=1;p->source_video_format=1;p->source_audio_format=1;p->output_pixel_format=1;p->color_primaries=1;p->color_transfer=1;p->color_matrix=1;p->color_range=1;p->rate_control=1;p->crf=20;p->preset=ODM_EXPORT_PRESET_ULTRAFAST;p->video_threads=1;p->audio_bitrate_kbps=128;p->flags=ODM_EXPORT_FLAG_FASTSTART;}
static odm_status states(void*u,uint64_t fi,int64_t sample,odm_composition_frame_state*c,odm_director_frame_state*d){uint64_t ti=(uint64_t)sample/ODM_MUSIC_TICK_SAMPLES;uint32_t i;(void)u;(void)fi;memset(c,0,sizeof(*c));memset(d,0,sizeof(*d));c->schema_version=1;c->mode=ODM_COMPOSITION_MODE_FLOW;c->tick_index=ti;c->center_sample=ti*ODM_MUSIC_TICK_SAMPLES;c->core_breath_q31=q(1,8);c->radial_gain_q31=q(3,4);c->grid_q31=q(2,3);c->particles_q31=q(1,2);c->ring_phase=(uint32_t)(ti*101u);for(i=0;i<48;i++)c->radial_q31[i]=(uint32_t)(((uint64_t)INT32_MAX*(i+1u))/48u);d->schema_version=ODM_DIRECTOR_SCHEMA_VERSION;d->layout=ODM_DIRECTOR_LAYOUT_ORBIT;d->previous_layout=ODM_DIRECTOR_LAYOUT_MONOLITH;d->tick_index=ti;d->depth_q31=q(1,2);d->edge_activity_q31=q(1,3);d->orbit_phase=(uint32_t)(ti*17u);return ODM_STATUS_OK;}
static odm_status core(void*u,uint64_t fi,int64_t sample,odm_render_surface_frame*s){provider_ctx*p=(provider_ctx*)u;(void)fi;memset(s,0,sizeof(*s));s->width=4;s->height=4;s->pixel_format=ODM_RENDER_SURFACE_RGBA8;s->primaries=ODM_COLOR_PRIMARIES_BT709;s->transfer=ODM_COLOR_TRANSFER_SRGB;s->alpha_mode=ODM_ALPHA_STRAIGHT;s->start_sample=sample;s->end_sample=sample+1;s->pixel_bytes=64;s->pixels=p->px;return ODM_STATUS_OK;}
static odm_status begin(void*u,const odm_export_recipe*r){file_sink*s=(file_sink*)u;(void)r;if(mkdir(s->stage_dir,0700)!=0)return ODM_STATUS_INTERNAL_ERROR;s->v=fopen(s->vp,"wb");if(!s->v){rmdir(s->stage_dir);return ODM_STATUS_INTERNAL_ERROR;}s->a=fopen(s->ap,"wb");if(!s->a){fclose(s->v);s->v=NULL;remove(s->vp);rmdir(s->stage_dir);return ODM_STATUS_INTERNAL_ERROR;}s->active=1;return ODM_STATUS_OK;}
static odm_status wv(void*u,uint64_t fi,int64_t sample,const uint8_t*p,uint64_t n){file_sink*s=(file_sink*)u;(void)fi;(void)sample;if(!s->v||fwrite(p,1,(size_t)n,s->v)!=(size_t)n)return ODM_STATUS_INTERNAL_ERROR;return ODM_STATUS_OK;}
static odm_status wa(void*u,uint64_t start,const uint8_t*p,uint64_t frames){file_sink*s=(file_sink*)u;(void)start;if(!s->a||fwrite(p,8,(size_t)frames,s->a)!=(size_t)frames)return ODM_STATUS_INTERNAL_ERROR;return ODM_STATUS_OK;}
static odm_status commit(void*u,const uint8_t*r,uint64_t n){file_sink*s=(file_sink*)u;FILE*rf;if(!s->active)return ODM_STATUS_INVALID_STATE;if(fclose(s->v)!=0){s->v=NULL;return ODM_STATUS_INTERNAL_ERROR;}s->v=NULL;if(fclose(s->a)!=0){s->a=NULL;return ODM_STATUS_INTERNAL_ERROR;}s->a=NULL;rf=fopen(s->rp,"wb");if(!rf)return ODM_STATUS_INTERNAL_ERROR;if(fwrite(r,1,(size_t)n,rf)!=(size_t)n||fclose(rf)!=0)return ODM_STATUS_INTERNAL_ERROR;if(rename(s->stage_dir,s->final_dir)!=0)return ODM_STATUS_INTERNAL_ERROR;s->active=0;return ODM_STATUS_OK;}
static void abortx(void*u,odm_status reason){file_sink*s=(file_sink*)u;(void)reason;if(s->v)fclose(s->v);if(s->a)fclose(s->a);s->v=NULL;s->a=NULL;remove(s->vp);remove(s->ap);remove(s->rp);rmdir(s->stage_dir);s->active=0;}
int main(int argc,char**argv){odm_layered_config c;odm_export_plan lp;odm_export_profile ep;odm_export_recipe er;odm_export_run_request rq;odm_export_sink sk;odm_export_run_receipt rr;provider_ctx pc;file_sink fs;odm_pcm_stereo_q31*pcm;uint8_t *frame,*scratch,receipt[ODM_EXPORT_RUN_RECEIPT_BYTES];uint64_t fb,sb,w,rn,argvn;uint32_t argcnt;char argb[ODM_EXPORT_ARGV_MAX_BYTES];FILE*f;uint64_t i;odm_status st;if(argc!=2)return 2;memset(&pc,0,sizeof(pc));for(i=0;i<64;i+=4){pc.px[i]=40;pc.px[i+1]=120;pc.px[i+2]=220;pc.px[i+3]=255;}cfg(&c);prof(&ep);if(odm_export_plan_build(&c,4801,4801,ODM_LAYERED_PIXEL_RGBA8_SRGB_BLACK_COMPOSITE,&lp)!=0)return 3;if(odm_export_recipe_build(&lp,&ep,&er)!=0)return 4;pcm=(odm_pcm_stereo_q31*)calloc((size_t)er.audio_source_frames,sizeof(*pcm));if(!pcm)return 5;for(i=0;i<er.audio_source_frames;i++){pcm[i].left=(int32_t)(i*1000u);pcm[i].right=-(int32_t)(i*1000u);}memset(&rq,0,sizeof(rq));rq.schema_version=ODM_EXPORT_RUN_SCHEMA_VERSION;rq.config=&c;rq.recipe=&er;rq.state_provider=states;rq.core_provider=core;rq.core_user=&pc;rq.canonical_pcm=pcm;rq.canonical_pcm_frames=er.audio_source_frames;if(odm_export_run_requirements(&rq,&fb,&sb,&w)!=0)return 6;frame=(uint8_t*)malloc((size_t)fb);scratch=(uint8_t*)malloc((size_t)sb);if(!frame||!scratch)return 7;memset(&fs,0,sizeof(fs));if(snprintf(fs.stage_dir,sizeof(fs.stage_dir),"%s/export.part",argv[1])<0||snprintf(fs.final_dir,sizeof(fs.final_dir),"%s/export.final",argv[1])<0||snprintf(fs.vp,sizeof(fs.vp),"%s/video.rgba",fs.stage_dir)<0||snprintf(fs.ap,sizeof(fs.ap),"%s/audio.s32le",fs.stage_dir)<0||snprintf(fs.rp,sizeof(fs.rp),"%s/receipt.bin",fs.stage_dir)<0)return 8;memset(&sk,0,sizeof(sk));sk.user=&fs;sk.begin=begin;sk.write_video=wv;sk.write_audio=wa;sk.commit=commit;sk.abort=abortx;st=odm_export_run(&rq,&sk,scratch,sb,frame,fb,receipt,sizeof(receipt),&rn,&rr);if(st!=0){fprintf(stderr,"run=%d\n",st);return 9;}if(odm_export_ffmpeg_argv_template(&er,argb,sizeof(argb),&argvn,&argcnt)!=0)return 12;{char path[512];if(snprintf(path,sizeof(path),"%s/argv.bin",argv[1])<0)return 13;f=fopen(path,"wb");if(!f||fwrite(argb,1,(size_t)argvn,f)!=(size_t)argvn)return 14;fclose(f);}printf("frames=%llu video_bytes=%llu audio_frames=%llu audio_bytes=%llu argv_tokens=%u\n",(unsigned long long)rr.frame_count,(unsigned long long)rr.video_bytes,(unsigned long long)rr.audio_frames,(unsigned long long)rr.audio_bytes,argcnt);free(frame);free(scratch);free(pcm);return 0;}
