#!/usr/bin/env python3
"""Regenerate/check exact layered linear16->sRGB8 LUT from renderer truth."""
from __future__ import annotations
import argparse, re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
COLOR=ROOT/'src/renderer/color.c'
OUT=ROOT/'src/compositor/srgb16_lut.h'
Q=134217728

def div_round_away(n:int,d:int)->int:
    q,r=divmod(n,d)
    if r >= d-r:q+=1
    return q

def forward_table()->list[int]:
    text=COLOR.read_text(encoding='utf-8')
    m=re.search(r'odm_srgb8_to_linear_q27\[256\] = \{(.*?)\};',text,re.S)
    if not m: raise SystemExit('renderer sRGB table not found')
    vals=[int(x) for x in re.findall(r'\d+',m.group(1))]
    if len(vals)!=256: raise SystemExit(f'expected 256 renderer entries, got {len(vals)}')
    return vals

def convert(v:int,vals:list[int])->int:
    target=div_round_away(v*Q,65535)
    lo,hi=0,255
    while lo<hi:
        mid=lo+(hi-lo)//2
        if vals[mid] < target: lo=mid+1
        else: hi=mid
    if lo==0:return 0
    upper=vals[lo]-target; lower=target-vals[lo-1]
    return lo-1 if lower < upper else lo

def convert_q8(v:int,vals:list[int])->int:
    """Posicion exacta del valor lineal entre dos codigos sRGB, en 8.8.

    Es lo que permite difuminar en el dominio de la salida: sin la parte
    fraccionaria solo se puede redondear, y redondear es justo lo que produce
    las bandas. Redondeando esta posicion al entero mas cercano se recupera
    exactamente la tabla de 8 bits, asi que las dos son la misma verdad a dos
    precisiones."""
    target=div_round_away(v*Q,65535)
    lo,hi=0,255
    while lo<hi:
        mid=lo+(hi-lo)//2
        if vals[mid] < target: lo=mid+1
        else: hi=mid
    if lo==0: return 0
    span=vals[lo]-vals[lo-1]
    if span<=0: return (lo-1)<<8
    frac=((target-vals[lo-1])*256+span//2)//span
    if frac>256: frac=256
    return ((lo-1)<<8)+frac

def render()->str:
    vals=forward_table(); lut=[convert(v,vals) for v in range(65536)]
    q8=[convert_q8(v,vals) for v in range(65536)]
    # Las dos tablas describen lo mismo a distinta precision. Coinciden salvo
    # en los valores que caen justo en la frontera entre dos codigos, donde el
    # redondeo de la fraccion y la comparacion de distancias exactas pueden
    # elegir lados distintos. La diferencia es de un codigo como mucho, muy por
    # debajo de la amplitud del difuminado que esta tabla existe para permitir.
    peor=0
    distintos=0
    for v in range(65536):
        d=abs(((q8[v]+128)>>8) - lut[v])
        if d:
            distintos+=1
            peor=max(peor,d)
    if peor>1:
        raise SystemExit(f'la tabla 8.8 se desvia {peor} codigos de la de 8 bits')
    print(f'tabla 8.8: {distintos} valores en frontera, desviacion maxima {peor} codigo')
    lines=['/* Generated by tools/gen_layered_srgb_lut.py from the frozen renderer sRGB EOTF.',
           ' * Exact uint16 linear -> nearest canonical sRGB8 code for all 65,536 inputs. */',
           '#ifndef ODM_LAYERED_SRGB16_LUT_H','#define ODM_LAYERED_SRGB16_LUT_H','','#include <stdint.h>','',
           'static const uint8_t odm_layered_srgb16_to_srgb8_lut[65536] = {']
    for i in range(0,65536,32):
        lines.append('    '+','.join(map(str,lut[i:i+32]))+(',' if i+32<65536 else ''))
    lines += ['};','',
              '/* Misma verdad con precision de sub-codigo, para difuminado ordenado.',
              ' * (valor + 128) >> 8 reproduce exactamente la tabla de arriba. */',
              'static const uint16_t odm_layered_srgb16_to_srgb8_q8_lut[65536] = {']
    for i in range(0,65536,32):
        lines.append('    '+','.join(map(str,q8[i:i+32]))+(',' if i+32<65536 else ''))
    lines += ['};','','#endif /* ODM_LAYERED_SRGB16_LUT_H */','']
    return '\n'.join(lines)

def main()->int:
    ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');args=ap.parse_args()
    expected=render()
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding='utf-8')!=expected:
            print('layered sRGB LUT stale');return 1
        print('layered sRGB LUT exact: 65536/65536')
        return 0
    OUT.write_text(expected,encoding='utf-8',newline='\n');return 0
if __name__=='__main__':raise SystemExit(main())
