#!/usr/bin/env python3
"""Regenerate/check exact layered linear16->sRGB8 LUT from renderer truth."""
from __future__ import annotations
import argparse, re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
COLOR=ROOT/'src/renderer/color.c'
OUT=ROOT/'src/compositor/srgb16_lut.h'
Q=134217728

def div_round_away(n:int,d:int)->int:
    q,r=divmod(n,d)
    if r >= d-r:q+=1
    return q

def forward_table()->list[int]:
    text=COLOR.read_text(encoding='utf-8')
    m=re.search(r'odm_srgb8_to_linear_q27\[256\] = \{(.*?)\};',text,re.S)
    if not m: raise SystemExit('renderer sRGB table not found')
    vals=[int(x) for x in re.findall(r'\d+',m.group(1))]
    if len(vals)!=256: raise SystemExit(f'expected 256 renderer entries, got {len(vals)}')
    return vals

def convert(v:int,vals:list[int])->int:
    target=div_round_away(v*Q,65535)
    lo,hi=0,255
    while lo<hi:
        mid=lo+(hi-lo)//2
        if vals[mid] < target: lo=mid+1
        else: hi=mid
    if lo==0:return 0
    upper=vals[lo]-target; lower=target-vals[lo-1]
    return lo-1 if lower < upper else lo

def render()->str:
    vals=forward_table(); lut=[convert(v,vals) for v in range(65536)]
    lines=['/* Generated by tools/gen_layered_srgb_lut.py from the frozen renderer sRGB EOTF.',
           ' * Exact uint16 linear -> nearest canonical sRGB8 code for all 65,536 inputs. */',
           '#ifndef ODM_LAYERED_SRGB16_LUT_H','#define ODM_LAYERED_SRGB16_LUT_H','','#include <stdint.h>','',
           'static const uint8_t odm_layered_srgb16_to_srgb8_lut[65536] = {']
    for i in range(0,65536,32):
        lines.append('    '+','.join(map(str,lut[i:i+32]))+(',' if i+32<65536 else ''))
    lines += ['};','','#endif /* ODM_LAYERED_SRGB16_LUT_H */','']
    return '\n'.join(lines)

def main()->int:
    ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');args=ap.parse_args()
    expected=render()
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding='utf-8')!=expected:
            print('layered sRGB LUT stale');return 1
        print('layered sRGB LUT exact: 65536/65536')
        return 0
    OUT.write_text(expected,encoding='utf-8',newline='\n');return 0
if __name__=='__main__':raise SystemExit(main())
