#!/usr/bin/env python3
"""Generate deterministic source identity and live module line counts."""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODULES = ROOT / "src" / "spine" / "modules.def"
MODULE_RE = re.compile(
    r'^ODM_MODULE\(\s*([A-Z0-9_]+)\s*,\s*[^,]+,\s*"[^"]+"\s*,\s*"([^"]+)"'
)
TEXT_SUFFIXES = {".c", ".h", ".def", ".py", ".md", ".txt", ".bad", ".rgba16le", ".json", ".dart"}


def module_paths() -> list[tuple[str, Path]]:
    result: list[tuple[str, Path]] = []
    for line in MODULES.read_text(encoding="utf-8").splitlines():
        match = MODULE_RE.match(line.strip())
        if match:
            result.append((match.group(1), ROOT / match.group(2)))
    if not result:
        raise SystemExit("modules.def contains no parseable ODM_MODULE entries")
    return result


def identity_inputs() -> list[Path]:
    paths: set[Path] = set()
    for directory in ("include", "src", "tests", "tools", "docs", "bench", "flutter"):
        base = ROOT / directory
        if base.exists():
            for path in base.rglob("*"):
                if path.is_file() and path.suffix in TEXT_SUFFIXES and "__pycache__" not in path.parts:
                    paths.add(path)
    for name in (
        "Makefile",
        "GATES.md",
        "ODPAR_MUSIC_CONSTITUTION_v0.md",
        "START_IMPLEMENTATION.md",
        "NEXT_CHAT_PROMPT.txt",
        "README.md",
    ):
        path = ROOT / name
        if path.is_file():
            paths.add(path)
    return sorted(paths, key=lambda item: item.relative_to(ROOT).as_posix())


def source_id(paths: list[Path]) -> str:
    digest = hashlib.sha256()
    for path in paths:
        relative = path.relative_to(ROOT).as_posix().encode("utf-8")
        data = path.read_bytes()
        digest.update(len(relative).to_bytes(8, "little"))
        digest.update(relative)
        digest.update(len(data).to_bytes(8, "little"))
        digest.update(data)
    return digest.hexdigest()


def line_count(path: Path) -> int:
    return path.read_bytes().count(b"\n")


def render() -> str:
    modules = module_paths()
    missing = [path for _, path in modules if not path.is_file()]
    if missing:
        raise SystemExit("missing registered modules: " + ", ".join(str(p) for p in missing))
    inputs = identity_inputs()
    lines = [
        "/* Generated by tools/gen_build_meta.py. Do not edit. */",
        "#ifndef ODM_BUILD_META_H",
        "#define ODM_BUILD_META_H",
        "",
        f'#define ODM_BUILD_SOURCE_ID "sha256:{source_id(inputs)}"',
        f"#define ODM_INVENTORY_SOURCE_FILE_COUNT {len(modules)}u",
        f"#define ODM_INVENTORY_SOURCE_LINE_COUNT {sum(line_count(p) for _, p in modules)}u",
    ]
    for symbol, path in modules:
        lines.append(f"#define ODM_MODULE_LINES_{symbol} {line_count(path)}u")
    lines.extend(
        [
            "",
            "#if defined(__clang__)",
            '#define ODM_BUILD_COMPILER_ID "clang-" __clang_version__',
            "#elif defined(__GNUC__)",
            '#define ODM_BUILD_COMPILER_ID "gcc-" __VERSION__',
            "#else",
            '#define ODM_BUILD_COMPILER_ID "unknown-c11-compiler"',
            "#endif",
            "",
            "#endif /* ODM_BUILD_META_H */",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != expected:
            print(f"stale build metadata: {args.output}")
            return 1
        print(f"build metadata current: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if args.output.is_file() and args.output.read_text(encoding="utf-8") == expected:
        return 0
    temporary = args.output.with_suffix(args.output.suffix + ".tmp")
    temporary.write_text(expected, encoding="utf-8", newline="\n")
    temporary.replace(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
