plugins { id 'com.android.application' }

android {
    namespace 'com.odpar.musicmotionlab'
    compileSdk 35
    ndkVersion '29.0.14206865'

    defaultConfig {
        applicationId 'com.odpar.musicmotionlab'
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName '0.52-lab1'
        ndk { abiFilters 'arm64-v8a' }
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_static", "-DODPAR_ENGINE_ROOT=${rootProject.projectDir}/../engine_official"
                cFlags '-O3', '-fvisibility=hidden', '-fstack-protector-strong'
            }
        }
    }
    buildTypes {
        debug { debuggable true; jniDebuggable false; minifyEnabled false }
        release { minifyEnabled false; debuggable false }
    }
    externalNativeBuild {
        cmake { path file('src/main/cpp/CMakeLists.txt'); version '3.22.1' }
    }
    packagingOptions { jniLibs { useLegacyPackaging true } }
}
